
export  const translate = {
  ADDRESS: {
    ADDRESS_FORM: {
      LABEL_STREET: 'ADDRESS.ADDRESS_FORM.LABEL_STREET',
      HELPER_TEXT_STREET: 'ADDRESS.ADDRESS_FORM.HELPER_TEXT_STREET',
      LABEL_ZIP: 'ADDRESS.ADDRESS_FORM.LABEL_ZIP',
      HELPER_TEXT_ZIP: 'ADDRESS.ADDRESS_FORM.HELPER_TEXT_ZIP',
      VALIDATION_FORMAT_ZIP: 'ADDRESS.ADDRESS_FORM.VALIDATION_FORMAT_ZIP',
      LABEL_CITY: 'ADDRESS.ADDRESS_FORM.LABEL_CITY',
      HELPER_TEXT_CITY: 'ADDRESS.ADDRESS_FORM.HELPER_TEXT_CITY',
      LABEL_STATE: 'ADDRESS.ADDRESS_FORM.LABEL_STATE',
      HELPER_TEXT_STATE: 'ADDRESS.ADDRESS_FORM.HELPER_TEXT_STATE',
      LABEL_ADDRESS_TYPE: 'ADDRESS.ADDRESS_FORM.LABEL_ADDRESS_TYPE',
      HELPER_TEXT_ADDRESS_TYPE: 'ADDRESS.ADDRESS_FORM.HELPER_TEXT_ADDRESS_TYPE',
      LABEL_DESCRIPTION: 'ADDRESS.ADDRESS_FORM.LABEL_DESCRIPTION',
      HELPER_TEXT_DESCRIPTION: 'ADDRESS.ADDRESS_FORM.HELPER_TEXT_DESCRIPTION',
      DIALOG_TITLE_INSERT: 'ADDRESS.ADDRESS_FORM.DIALOG_TITLE_INSERT',
      DIALOG_TITLE_EDIT: 'ADDRESS.ADDRESS_FORM.DIALOG_TITLE_EDIT',
      DIALOG_TITLE_DELETE: 'ADDRESS.ADDRESS_FORM.DIALOG_TITLE_DELETE',
      DIALOG_DELETE_ADDRESS_MESSAGE: 'ADDRESS.ADDRESS_FORM.DIALOG_DELETE_ADDRESS_MESSAGE',
    },
    ADDRESS_TAG: {
      LABEL_ADDRESS:'ADDRESS.ADDRESS_TAG.LABEL_ADDRESS'
    },
    ADDRESS_VIEW: {
      TITLE: 'ADDRESS.ADDRESS_VIEW.TITLE',
      BUTTON_ADD: 'ADDRESS.ADDRESS_VIEW.BUTTON_ADD',
    }
  },

  BANK_TRANSACTION:{
    COMMON:{
      RENDERS_BANKS_HEADER_TRANSACTIONS:{
        TITLE: 'BANK_TRANSACTION'
      }
    },
    FORM:{
      HEADER:{
        ACCOUNT_BALANCE:{
          TITLE: 'BANK_TRANSACTION.FORM.HEADER.ACCOUNT_BALANCE.TITLE',
          PREVIOUS_BALANCE_LABEL: 'BANK_TRANSACTION.FORM.HEADER.ACCOUNT_BALANCE.PREVIOUS_BALANCE_LABEL',
          IN_FINANCE_LABEL: 'BANK_TRANSACTION.FORM.HEADER.ACCOUNT_BALANCE.IN_FINANCE_LABEL',
          OUT_FINANCE_LABEL: 'BANK_TRANSACTION.FORM.HEADER.ACCOUNT_BALANCE.OUT_FINANCE_LABEL',
          NEW_BALANCE_LABEL: 'BANK_TRANSACTION.FORM.HEADER.ACCOUNT_BALANCE.NEW_BALANCE_LABEL',
          IN_COUNT_LABEL: 'BANK_TRANSACTION.FORM.HEADER.ACCOUNT_BALANCE.IN_COUNT_LABEL',
          OUT_COUNT_LABEL: 'BANK_TRANSACTION.FORM.HEADER.ACCOUNT_BALANCE.OUT_COUNT_LABEL',
        },
        FORM:{
          BANK_ACCOUNT_LABEL: 'BANKS_TRANSACTION.FORM.HEADER.FORM.BANK_ACCOUNT_LABEL',
          DATA_PROCESSED_LABEL:'BANKS_TRANSACTION.FORM.HEADER.FORM.DATA_PROCESSED_LABEL',
          DOCUMENT_ID_LABEL: 'BANKS_TRANSACTION.FORM.HEADER.FORM.DOCUMENT_ID_LABEL',
          DESCRIPTION_LABEL: 'BANKS_TRANSACTION.FORM.HEADER.FORM.DESCRIPTION_LABEL',
          DIALOG_TITLE_BANK_HEADER_TRANSACTION: 'BANKS_TRANSACTION.FORM.HEADER.FORM.DIALOG_TITLE_BANK_HEADER_TRANSACTION'

        },
        HEADER:{
          BANK_ACCOUNT_LABEL: 'BANKS_TRANSACTION.FORM.HEADER.HEADER.BANK_ACCOUNT_LABEL',
          DATA_PROCESSED_LABEL: 'BANKS_TRANSACTION.FORM.HEADER.HEADER.DATA_PROCESSED_LABEL',
          DOCUMENT_ID_LABEL: 'BANKS_TRANSACTION.FORM.HEADER.HEADER.DOCUMENT_ID_LABEL',
          DESCRIPTION_LABEL: 'BANKS_TRANSACTION.FORM.HEADER.HEADER.DESCRIPTION_LABEL'

        }
      },
      APP_BAR_BUTTON_HEADER_LABEL:'BANKS_TRANSACTION.FORM.APP_BAR_BUTTON_HEADER_LABEL',
      APP_BAR_BUTTON_PREVIEW_LABEL:'BANKS_TRANSACTION.FORM.APP_BAR_BUTTON_PREVIEW_LABEL',
      APP_BAR_BUTTON_FINISH_LABEL:'BANKS_TRANSACTION.FORM.APP_BAR_BUTTON_FINISH_LABEL',
      BUTTON_UPLOAD_LABEL: 'BANKS_TRANSACTION.FORM.BUTTON_UPLOAD_LABEL',
      DIALOG_SAVE_BANK_TRANSACTION_MESSAGE:'BANKS_TRANSACTION.FORM.DIALOG_SAVE_BANK_TRANSACTION_MESSAGE',
      DIALOG_SAVE_BANK_TRANSACTION_TITLE_FINISH_BANK_TRANSACTION:'BANKS_TRANSACTION.FORM.DIALOG_SAVE_BANK_TRANSACTION_TITLE_FINISH_BANK_TRANSACTION'

    },
    ITEMS:{
      COMMON:{
        RENDERS_BANK_TRANSACTION:{
          TOTAL: 'BANK_TRANSACTION.FORM.ITEMS.COMMON.RENDERS_BANK_TRANSACTION.TOTAL',
          EXP: 'BANK_TRANSACTION.FORM.ITEMS.COMMON.RENDERS_BANK_TRANSACTION.EXP'
        }
      },
      TRANSACTION_TABLE:{
        NAME_LABEL:'BANK_TRANSACTION.FORM.ITEMS.TRANSACTION_TABLE.NAME_LABEL',
        DATES_LABEL:'BANK_TRANSACTION.FORM.ITEMS.TRANSACTION_TABLE.DATES_LABEL',
        OUT_FINANCE_LABEL: 'BANK_TRANSACTION.FORM.ITEMS.TRANSACTION_TABLE.OUT_FINANCE_LABEL',
        IN_FINANCE_LABEL: 'BANK_TRANSACTION.FORM.ITEMS.TRANSACTION_TABLE.IN_FINANCE_LABEL',
        EXPENSE_LABEL:'BANK_TRANSACTION.FORM.ITEMS.TRANSACTION_TABLE.EXPENSE_LABEL',
        CODE_LABEL: 'BANK_TRANSACTION.FORM.ITEMS.TRANSACTION_TABLE.CODE_LABEL',
        DESCRIPTION_LABEL: 'BANK_TRANSACTION.FORM.ITEMS.TRANSACTION_TABLE.DESCRIPTION_LABEL',
        MODEL_LABEL:'BANK_TRANSACTION.FORM.ITEMS.TRANSACTION_TABLE.MODEL_LABEL',
        TRANSACTION_LABEL:'BANK_TRANSACTION.FORM.ITEMS.TRANSACTION_TABLE.TRANSACTION_LABEL',
      }
    },
    PDF:{
      PDF:{
        PDF_TITLE:'BANK_TRANSACTION.PDF.PDF.PDF_TITLE',
        DIALOG_PDF_BANK_TRANSACTION_LABEL_RB: 'BANK_TRANSACTION.PDF.PDF.DIALOG_PDF_BANK_TRANSACTION_LABEL_RB',
        DIALOG_PDF_BANK_TRANSACTION_LABEL_NAME:'BANK_TRANSACTION.PDF.PDF.DIALOG_PDF_BANK_TRANSACTION_LABEL_NAME',
        DIALOG_PDF_BANK_TRANSACTION_LABEL_DATES:'BANK_TRANSACTION.PDF.PDF.DIALOG_PDF_BANK_TRANSACTION_LABEL_DATES',
        DIALOG_PDF_BANK_TRANSACTION_LABEL_FINANCE:'BANK_TRANSACTION.PDF.PDF.DIALOG_PDF_BANK_TRANSACTION_LABEL_FINANCE',
        DIALOG_PDF_BANK_TRANSACTION_LABEL_CODE:'BANK_TRANSACTION.PDF.PDF.DIALOG_PDF_BANK_TRANSACTION_LABEL_CODE',
        DIALOG_PDF_BANK_TRANSACTION_LABEL_DESCRIPTION:'BANK_TRANSACTION.PDF.PDF.DIALOG_PDF_BANK_TRANSACTION_LABEL_DESCRIPTION',
        DIALOG_PDF_BANK_TRANSACTION_LABEL_MODEL:'BANK_TRANSACTION.PDF.PDF.DIALOG_PDF_BANK_TRANSACTION_LABEL_MODEL',
        DIALOG_PDF_BANK_TRANSACTION_LABEL_TRANSACTION:'BANK_TRANSACTION.PDF.PDF.DIALOG_PDF_BANK_TRANSACTION_LABEL_TRANSACTION',
        DIALOG_PDF_BANK_TRANSACTION_CENTERED_DIALOG_TITLE_BANKS_TRANSACTION_PDF:'BANK_TRANSACTION.PDF.PDF.DIALOG_PDF_BANK_TRANSACTION_CENTERED_DIALOG_TITLE_BANKS_TRANSACTION_PDF',

      }
    },
    PREVIEW:{
      HEADER:{
        PLACEHOLDER_BANK_NAME:'BANK_TRANSACTION.PREVIEW.HEADER.PLACEHOLDER_BANK_NAME',
        LABEL_DATE: 'BANK_TRANSACTION.PREVIEW.HEADER.LABEL.DATE',
        LABEL_DOCUMENT_ID: 'BANK_TRANSACTION.PREVIEW.HEADER.LABEL.DOCUMENT_ID',
        LABEL_DESCRIPTION: 'BANK_TRANSACTION.PREVIEW.HEADER.LABEL_DESCRIPTION'

      },
      PREVIEW:{
        MESSAGE_ERROR:'BANK_TRANSACTION.PREVIEW.PREVIEW.MESSAGE_ERROR',
        DIALOG_PREVIEW_BANK_TRANSACTION_TITLE: 'BANK_TRANSACTION.PREVIEW.PREVIEW.DIALOG_PREVIEW_BANK_TRANSACTION_TITLE',

      }
    },
    VIEW:{
      BANK_ACCOUNT_BALANCE:{
        TITLE: 'BANK_TRANSACTION.VIEW.BANK_ACCOUNT_BALANCE.TITLE',
        LABEL_OWES: 'BANK_TRANSACTION.VIEW.BANK_ACCOUNT_BALANCE.LABEL_OWES',
        LABEL_CLAIMS: 'BANK_TRANSACTION.VIEW.BANK_ACCOUNT_BALANCE.LABEL_CLAIMS',
        LABEL_BALANCE: 'BANK_TRANSACTION.VIEW.BANK_ACCOUNT_BALANCE.LABEL_BALANCE'
      },
      FILTER:{
        BUTTON_SHORTCUT_LABEL_CLEAR: 'BANK_TRANSACTION.VIEW.FILTER.BUTTON_SHORTCUT_LABEL_CLEAR',
        BUTTON_SHORTCUT_LABEL_CUSTOMER: 'BANK_TRANSACTION.VIEW.FILTER.BUTTON_SHORTCUT_LABEL_CUSTOMER',
        INPUT_HELPER_TEXT_DATE_FROM: 'BANK_TRANSACTION.VIEW.FILTER.INPUT_HELPER_TEXT_DATE_FROM',
        INPUT_HELPER_TEXT_DATE_TO: 'BANK_TRANSACTION.VIEW.FILTER.INPUT_HELPER_TEXT_DATE_TO',
        SELECT_LABEL_BANK_ACCOUNT: 'BANK_TRANSACTION.VIEW.FILTER.SELECT_LABEL_BANK_ACCOUNT'

      }
    },
    MAIN_VIEW: {
      BANK_TRANSACTION_TABLE_HEADER_LABEL_DATE: 'BANK_TRANSACTION.MAIN_VIEW.BANK_TRANSACTION_TABLE_HEADER_LABEL_DATE',
      BANK_TRANSACTION_TABLE_HEADER_LABEL_ACCOUNT: 'BANK_TRANSACTION.MAIN_VIEW.BANK_TRANSACTION_TABLE_HEADER_LABEL_ACCOUNT',
      BANK_TRANSACTION_TABLE_HEADER_LABEL_DOCUMENT: 'BANK_TRANSACTION.MAIN_VIEW.BANK_TRANSACTION_TABLE_HEADER_LABEL_DOCUMENT',
      BANK_TRANSACTION_TABLE_HEADER_LABEL_FINANCE_IN: 'BANK_TRANSACTION.MAIN_VIEW.BANK_TRANSACTION_TABLE_HEADER_LABEL_FINANCE_IN',
      BANK_TRANSACTION_TABLE_HEADER_LABEL_FINANCE_OUT: 'BANK_TRANSACTION.MAIN_VIEW.BANK_TRANSACTION_TABLE_HEADER_LABEL_FINANCE_OUT',
      UNDO_BANK_TRANSACTION_LABEL_NEW_TRANSACTION: 'BANK_TRANSACTION.MAIN_VIEW.UNDO_BANK_TRANSACTION_LABEL_NEW_TRANSACTION',
      DIV_EXTERNAL_KEYBOARD_ROOT_TITLE_BANKS_TRANSACTION: 'BANK_TRANSACTION.MAIN_VIEW.DIV_EXTERNAL_KEYBOARD_ROOT_TITLE_BANKS_TRANSACTION',
      DIALOG_DELETE_BANK_TRANSACTION_MESSAGE: 'BANK_TRANSACTION.MAIN_VIEW.DIALOG_DELETE_BANK_TRANSACTION_MESSAGE',
      DIALOG_UNDO_BANK_TRANSACTION_TITLE: 'BANK_TRANSACTION.MAIN_VIEW.DIALOG_DELETE_BANK_TRANSACTION_TITLE'

    }
  },

  BANKS: {
    MODAL: {
      BANK_ACCOUNT_SEARCH: {
        TITLE: 'BANKS.MODAL.BANK_ACCOUNT_SEARCH.TITLE',
        AUTOCOMPLETE_HELPER_TEXT: 'BANKS.MODAL.BANK_ACCOUNT_SEARCH.AUTOCOMPLETE_HELPER_TEXT',
        BUTTON_CANCEL: 'BANKS.MODAL.BANK_ACCOUNT_SEARCH.BUTTON_CANCEL',
        BUTTON_OK: 'BANKS.MODAL.BANK_ACCOUNT_SEARCH.BUTTON_OK'
      }
    },
    VIEW: {
      BANK_ACCOUNT_VIEW: {
        CUSTOMER_NAME_PLACEHOLDER: 'BANKS.VIEW.BANK_ACCOUNT_VIEW.CUSTOMER_NAME_PLACEHOLDER',
        ERROR_MESSAGE: 'BANKS.VIEW.BANK_ACCOUNT_VIEW.ERROR_MESSAGE'
      }
    },
    BANK_ACCOUNT_FORM: {
      SELECT_BANK_LABEL: 'BANKS.BANK_ACCOUNT_FORM.SELECT_BANK_LABEL',
      SELECT_BANK_HELPER_TEXT: 'BANKS.BANK_ACCOUNT_FORM.SELECT_BANK_HELPER_TEXT',
      ACCOUNT_NUMBER_LABEL: 'BANKS.BANK_ACCOUNT_FORM.ACCOUNT_NUMBER_LABEL',
      ACCOUNT_NUMBER_FIRST_FIELD_VALIDATION_ARE_SAME_MESSAGE: 'BANKS.BANK_ACCOUNT_FORM.ACCOUNT_NUMBER_FIRST_FIELD_VALIDATION_ARE_SAME_MESSAGE',
      ACCOUNT_NUMBER_FIRST_FIELD_VALIDATION_FORMAT_MESSAGE : 'BANKS.BANK_ACCOUNT_FORM.ACCOUNT_NUMBER_FIRST_FIELD_VALIDATION_FORMAT',
      ACCOUNT_NUMBER_MIDDLE_FIELD_VALIDATION_FORMAT_MESSAGE: 'BANKS.BANK_ACCOUNT_FORM.ACCOUNT_NUMBER_MIDDLE_FIELD_VALIDATION_FORMAT_MESSAGE',
      ACCOUNT_NUMBER_LAST_FIELD_VALIDATION_FORMAT_MESSAGE: 'BANKS.BANK_ACCOUNT_FORM.ACCOUNT_NUMBER_LAST_FIELD_VALIDATION_FORMAT_MESSAGE',
      DIALOG_TITLE_INSERT: 'BANKS.BANK_ACCOUNT_FORM.DIALOG_TITLE_INSERT',
      DIALOG_TITLE_EDIT: 'BANKS.BANK_ACCOUNT_FORM.DIALOG_TITLE_EDIT',
      DIALOG_TITLE_DELETE: 'BANKS.BANK_ACCOUNT_FORM.DIALOG_TITLE_DELETE',
      DIALOG_DELETE_BANK_ACCOUNT_MESSAGE : 'BANKS.BANK_ACCOUNT_FORM.DIALOG_DELETE_BANK_ACCOUNT_MESSAGE'
    },
    BANK_ACCOUNT_VIEW: {
      TITLE: 'BANKS.BANK_ACCOUNT_VIEW.TITLE',
      BUTTON_ADD: 'BANKS.BANK_ACCOUNT_VIEW.BUTTON_ADD'
    }
  },
  CALCULATION: {
    COMMON: {
      SUMMARIZE_CELL: {
        SUMMARIZE_CELL_FINANCE_TEXT: 'CALCULATION.COMMON.SUMMARIZE_CELL.SUMMARIZE_CELL_FINANCE_TEXT',
        SUMMARIZE_CELL_TAX_EXP_TEXT: 'CALCULATION.COMMON.SUMMARIZE_CELL.SUMMARIZE_CELL_TAX_EXP_TEXT',
        SUMMARIZE_CELL_FINANCE_EXP_TEXT: 'CALCULATION.COMMON.SUMMARIZE_CELL.SUMMARIZE_CELL_FINANCE_EXP_TEXT',
        SUMMARIZE_CELL_TAX: 'CALCULATION.COMMON.SUMMARIZE_CELL.SUMMARIZE_CELL_TAX',
        SUMMARIZE_CELL_TAX_FINANCE_EXP: 'CALCULATION.COMMON.SUMMARIZE_CELL.SUMMARIZE_CELL_TAX_FINANCE_EXP'
      }
    },
    MODAL: {
      DOCUMENT_HEADER: {
        INVOICE_TAX: {
          INVOICE_TAX_FORM: {
            TAX_LABEL: 'CALCULATION.MODAL.DOCUMENT_HEADER.INVOICE_TAX.INVOICE_TAX_FORM.TAX_LABEL',
            HELPER_TEXT_TAX: 'CALCULATION.MODAL.DOCUMENT_HEADER.INVOICE_TAX.INVOICE_TAX_FORM.HELPER_TEXT_TAX',
            FINANCE_LABEL: 'CALCULATION.MODAL.DOCUMENT_HEADER.INVOICE_TAX.INVOICE_TAX_FORM.FINANCE_LABEL',
            HELPER_TEXT_FINANCE: 'CALCULATION.MODAL.DOCUMENT_HEADER.INVOICE_TAX.INVOICE_TAX_FORM.HELPER_TEXT_FINANCE',
            BUTTON_ADD_LABEL: 'CALCULATION.MODAL.DOCUMENT_HEADER.INVOICE_TAX.INVOICE_TAX_FORM.BUTTON_ADD_LABEL',
          }
        },
        ADDITIONAL_EXPENSE_PART: {
          BUTTON_ADD_LABEL: 'CALCULATION.MODAL.DOCUMENT_HEADER.ADDITIONAL_EXPENSE_PART.BUTTON_ADD_LABEL',
          TITLE: 'CALCULATION.MODAL.DOCUMENT_HEADER.ADDITIONAL_EXPENSE_PART.TITLE',
          TH_CUSTOMER: 'CALCULATION.MODAL.DOCUMENT_HEADER.ADDITIONAL_EXPENSE_PART.TH_CUSTOMER',
          TH_INVOICE_NUM: 'CALCULATION.MODAL.DOCUMENT_HEADER.ADDITIONAL_EXPENSE_PART.TH_INVOICE_NUM',
          TH_INVOICE_DATE: 'CALCULATION.MODAL.DOCUMENT_HEADER.ADDITIONAL_EXPENSE_PART.TH_INVOICE_DATE',
          TH_FINANCE_TOTAL: 'CALCULATION.MODAL.DOCUMENT_HEADER.ADDITIONAL_EXPENSE_PART.TH_FINANCE_TOTAL',
          TH_FINANCE_TAX: 'CALCULATION.MODAL.DOCUMENT_HEADER.ADDITIONAL_EXPENSE_PART.TH_FINANCE_TAX',
          TH_TAX_RECAPITULATION: 'CALCULATION.MODAL.DOCUMENT_HEADER.ADDITIONAL_EXPENSE_PART.TH_TAX_RECAPITULATION',
          TH_DUE_DATE: 'CALCULATION.MODAL.DOCUMENT_HEADER.ADDITIONAL_EXPENSE_PART.TH_DUE_DATE',
          TAX_NUMBER_LABEL: 'CALCULATION.MODAL.DOCUMENT_HEADER.ADDITIONAL_EXPENSE_PART.TAX_NUMBER_LABEL',
          SUPPLIER_NAME_LABEL : 'CALCULATION.MODAL.DOCUMENT_HEADER.ADDITIONAL_EXPENSE_PART.SUPPLIER_NAME_LABEL',
        },
        DUE_DATES_PART: {
          TITLE: 'CALCULATION.MODAL.DOCUMENT_HEADER.DUE_DATES_PART.TITLE',
          BUTTON_ADD_LABEL: 'CALCULATION.MODAL.DOCUMENT_HEADER.DUE_DATES_PART.BUTTON_ADD_LABEL',
          TOTAL_ADDED_LABEL: 'CALCULATION.MODAL.DOCUMENT_HEADER.DUE_DATES_PART.TOTAL_ADDED_LABEL',
          TOTAL_DUE_DATES_LABEL: 'CALCULATION.MODAL.DOCUMENT_HEADER.DUE_DATES_PART.TOTAL_DUE_DATES_LABEL',
        },
        INVOICE_EXPENSES: {
          TITLE: 'CALCULATION.MODAL.DOCUMENT_HEADER.INVOICE_EXPENSES.TITLE',
          BUTTON_ADD_LABEL: 'CALCULATION.MODAL.DOCUMENT_HEADER.INVOICE_EXPENSES.BUTTON_ADD_LABEL',
        },
        INVOICE_FINANCE_TAX: {
          TOTAL_FINANCE_MP_LABEL: 'CALCULATION.MODAL.DOCUMENT_HEADER.INVOICE_FINANCE_TAX.TOTAL_FINANCE_MP_LABEL',
          TOTAL_FINANCE_TAX_LABEL: 'CALCULATION.MODAL.DOCUMENT_HEADER.INVOICE_FINANCE_TAX.TOTAL_FINANCE_TAX_LABEL',
        },
        INVOICE_TAXES: {
          CHECKBOX_LABEL: 'CALCULATION.MODAL.DOCUMENT_HEADER.INVOICE_TAXES.CHECKBOX_LABEL',
          BUTTON_ADD_LABEL: 'CALCULATION.MODAL.DOCUMENT_HEADER.INVOICE_TAXES.BUTTON_ADD_LABEL',
          TITLE: 'CALCULATION.MODAL.DOCUMENT_HEADER.INVOICE_TAXES.TITLE'
        },
        SUPPLIER_INVOICE_WAREHOUSE_PART: {
          BUTTON_SUPPLIER_LABEL: 'CALCULATION.MODAL.DOCUMENT_HEADER.SUPPLIER_INVOICE_WAREHOUSE_PART.BUTTON_SUPPLIER_LABEL',
          INVOICE_NUMBER_LABEL: 'CALCULATION.MODAL.DOCUMENT_HEADER.SUPPLIER_INVOICE_WAREHOUSE_PART.INVOICE_NUMBER_LABEL',
          INVOICE_DATE_PICKER_LABEL: 'CALCULATION.MODAL.DOCUMENT_HEADER.SUPPLIER_INVOICE_WAREHOUSE_PART.INVOICE_DATE_PICKER_LABEL',
          SELECT_WAREHOUSE_LABEL: 'CALCULATION.MODAL.DOCUMENT_HEADER.SUPPLIER_INVOICE_WAREHOUSE_PART.SELECT_WAREHOUSE_LABEL',
          CALCULATION_DATE_PICKER_LABEL: 'CALCULATION.MODAL.DOCUMENT_HEADER.SUPPLIER_INVOICE_WAREHOUSE_PART.CALCULATION_DATE_PICKER_LABEL'
        }
      },
      FORMS: {
        ADDITIONAL_EXPENSE: {
          ADDITIONAL_EXPENSE_EXIST_ERROR_MESSAGE: 'CALCULATION.MODAL.DOCUMENT_HEADER.FORMS.ADDITIONAL_EXPENSE.ADDITIONAL_EXPENSE_EXIST_ERROR_MESSAGE',
          CUSTOMER_NAME_PLACEHOLDER : 'CALCULATION.MODAL.DOCUMENT_HEADER.FORMS.ADDITIONAL_EXPENSE.CUSTOMER_NAME_PLACEHOLDER',
          BUTTON_SUPPLIER_LABEL : 'CALCULATION.MODAL.DOCUMENT_HEADER.FORMS.ADDITIONAL_EXPENSE.BUTTON_SUPPLIER_LABEL',
          INVOICE_NUMBER_LABEL : 'CALCULATION.MODAL.DOCUMENT_HEADER.FORMS.ADDITIONAL_EXPENSE.INVOICE_NUMBER_LABEL',
          HELPER_TEXT_INVOICE_NUMBER: 'CALCULATION.MODAL.DOCUMENT_HEADER.FORMS.ADDITIONAL_EXPENSE.HELPER_TEXT_INVOICE_NUMBER',
          INVOICE_DATE_PICKER_LABEL: 'CALCULATION.MODAL.DOCUMENT_HEADER.FORMS.ADDITIONAL_EXPENSE.INVOICE_dATE_PICKER_LABEL',
          HELPER_TEXT_INVOICE_DATE_PICKER: 'CALCULATION.MODAL.DOCUMENT_HEADER.FORMS.ADDITIONAL_EXPENSE.HELPER_TEXT_INVOICE_DATE_PICKER',
          DUE_DATE_LABEL: 'CALCULATION.MODAL.DOCUMENT_HEADER.FORMS.ADDITIONAL_EXPENSE.DUE_DATE_LABEL',
          HELPER_TEXT_DUE_DATE : 'CALCULATION.MODAL.DOCUMENT_HEADER.FORMS.ADDITIONAL_EXPENSE.HELPER_TEXT_DUE_DATE',
          INVOICE_FINANCE_WITH_TAX_LABEL: 'CALCULATION.MODAL.DOCUMENT_HEADER.FORMS.ADDITIONAL_EXPENSE.INVOICE_FINANCE_WITH_TAX_LABEL',
          FINANCE_TAX_LABEL: 'CALCULATION.MODAL.DOCUMENT_HEADER.FORMS.ADDITIONAL_EXPENSE.FINANCE_TAX_LABEL',
          CHECKBOX_ADD_TAX_RECAPITULATION_LABEL: 'CALCULATION.MODAL.DOCUMENT_HEADER.FORMS.ADDITIONAL_EXPENSE.CHECKBOX_ADD_TAX_RECAPITULATION_LABEL',
        },
        DUE_DATE_FORM: {
          TOTAL_TO_ADD_LABEL: 'CALCULATION.MODAL.DOCUMENT_HEADER.FORMS.DUE_DATE_FORM.TOTAL_TO_ADD_LABEL',
          DUE_DATE_PICKER_LABEL: 'CALCULATION.MODAL.DOCUMENT_HEADER.FORMS.DUE_DATE_FORM.DATE_PICKER_LABEL',
          HELPER_TEXT_DUE_DATE_PICKER: 'CALCULATION.MODAL.DOCUMENT_HEADER.FORMS.DUE_DATE_FORM.HELPER_TEXT_DUE_DATE_PICKER',
          FINANCE_LABEL: 'CALCULATION.MODAL.DOCUMENT_HEADER.FORMS.DUE_DATE_FORM.FINANCE_LABEL',
          HELPER_TEXT_FINANCE: 'CALCULATION.MODAL.DOCUMENT_HEADER.FORMS.DUE_DATE_FORM.HELPER_TEXT_FINANCE',
          DESCRIPTION_LABEL : 'CALCULATION.MODAL.DOCUMENT_HEADER.FORMS.DUE_DATE_FORM.DESCRIPTION_LABEL',
          HELPER_TEXT_DESCRIPTION: 'CALCULATION.MODAL.DOCUMENT_HEADER.FORMS.DUE_DATE_FORM.HELPER_TEXT_DESCRIPTION',
          TITLE: 'CALCULATION.MODAL.DOCUMENT_HEADER.FORMS.DUE_DATE_FORM.TITLE'
        },
        EXPENSES_FORM: {
          TITLE: 'CALCULATION.MODAL.DOCUMENT_HEADER.FORMS.EXPENSES_FORM.TITLE',
          SELECT_TAX_LABEL: 'CALCULATION.MODAL.DOCUMENT_HEADER.FORMS.EXPENSES_FORM.SELECT_TAX_LABEL',
          HELPER_TEXT_SELECT_TAX: 'CALCULATION.MODAL.DOCUMENT_HEADER.FORMS.EXPENSES_FORM.HELPER_TEXT_SELECT_TAX',
          FINANCE_NO_VAT_LABEL: 'CALCULATION.MODAL.DOCUMENT_HEADER.FORMS.EXPENSES_FORM.FINANCE_NO_VAT_LABEL',
          HELPER_TEXT_FINANCE_NO_VAT: 'CALCULATION.MODAL.DOCUMENT_HEADER.FORMS.EXPENSES_FORM.HELPER_TEXT_FINANCE_NO_VAT',
          FINANCE_WITH_VAT_LABEL: 'CALCULATION.MODAL.DOCUMENT_HEADER.FORMS.EXPENSES_FORM.FINANCE_WITH_VAT_LABEL',
          HELPER_TEXT_FINANCE_WITH_VAT: 'CALCULATION.MODAL.DOCUMENT_HEADER.FORMS.EXPENSES_FORM.HELPER_TEXT_FINANCE_WITH_VAT',
          DESCRIPTION_LABEL: 'CALCULATION.MODAL.DOCUMENT_HEADER.FORMS.EXPENSES_FORM.DESCRIPTION_LABEL',
          HELPER_TEXT_DESCRIPTION: 'CALCULATION.MODAL.DOCUMENT_HEADER.FORMS.EXPENSES_FORM.HELPER_TEXT_DESCRIPTION',
        },
        INVOICE_TAX_DIALOG: {
          TITLE: 'CALCULATION.MODAL.DOCUMENT_HEADER.FORMS.INVOICE_TAX_DIALOG.TITLE',
          SELECT_TAX_LABEL : 'CALCULATION.MODAL.DOCUMENT_HEADER.FORMS.INVOICE_TAX_DIALOG.SELECT_TAX_LABEL',
          HELPER_TEXT_SELECT_TAX : 'CALCULATION.MODAL.DOCUMENT_HEADER.FORMS.INVOICE_TAX_DIALOG.HELPER_TEXT_SELECT_TAX',
          FINANCE_NO_VAT_LABEL: 'CALCULATION.MODAL.DOCUMENT_HEADER.FORMS.INVOICE_TAX_DIALOG.FINANCE_NO_VAT_LABEL',
          VAT_LABEL: 'CALCULATION.MODAL.DOCUMENT_HEADER.FORMS.INVOICE_TAX_DIALOG.VAT_LABEL',
          HELPER_TEXT_VAT: 'CALCULATION.MODAL.DOCUMENT_HEADER.FORMS.INVOICE_TAX_DIALOG.HELPER_TEXT_VAT',
          FINANCE_WITH_VAT_LABEL: 'CALCULATION.MODAL.DOCUMENT_HEADER.FORMS.INVOICE_TAX_DIALOG.FINANCE_WITH_VAT_LABEL',
        }
      },
      DOCUMENT_HEADER_FORM: {
        SUPPLIER_ERROR_MESSAGE: 'CALCULATION.MODAL.DOCUMENT_HEADER_FORM.SUPPLIER_ERROR_MESSAGE',
        CALCULATION_HEADER_NUMBER_LABEL: 'CALCULATION.MODAL.DOCUMENT_HEADER_FORM.CALCULATION_HEADER_NUMBER_LABEL',
        DIALOG_HEADER_TITLE: 'CALCULATION.MODAL.DOCUMENT_HEADER_FORM.DIALOG_HEADER_TITLE'
      }
    },
    PDF: {
      COMMON: {
        CUSTOMER_SPEC: {
          TAX_NUMBER_LABEL : 'CALCULATION.PDF.COMMON.CUSTOMER_SPEC.TAX_NUMBER_LABEL',
          COMPANY_NUMBER_LABEL: 'CALCULATION.PDF.COMMON.CUSTOMER_SPEC.COMPANY_NUMBER_LABEL'
        },
        PRICE_DIFFERENCE: {
          TITLE: 'CALCULATION.PDF.COMMON.PRICE_DIFFERENCE.TITLE',
          PRICE_LABEL: 'CALCULATION.PDF.COMMON.PRICE_DIFFERENCE.PRICE_LABEL',
          NEW_PRICE_LABEL: 'CALCULATION.PDF.COMMON.PRICE_DIFFERENCE.NEW_PRICE_LABEL'
        },
        RENDER_COLUMN : {
          INVOICE_LABEL: 'CALCULATION.PDF.COMMON.RENDER_COLUMN.INVOICE_LABEL',
          QTY_LABEL: 'CALCULATION.PDF.COMMON.RENDER_COLUMN.QTY_LABEL',
          PRICE_LABEL: 'CALCULATION.PDF.COMMON.RENDER_COLUMN.PRICE_LABEL',
          FINANCE_LABEL: 'CALCULATION.PDF.COMMON.RENDER_COLUMN.FINANCE_LABEL'
        },
        VAT_RENDER: {
          TITLE: 'CALCULATION.PDF.COMMON.VAT_RENDER.TITLE',
          FINANCE_LABEL: 'CALCULATION.PDF.COMMON.VAT_RENDER.FINANCE_LABEL'
        }
      },
      FOOTER: {
        ADDITIONAL_EXPENSE_PART : {
          TITLE: 'CALCULATION.PDF.FOOTER.ADDITIONAL_EXPENSE_PART.TITLE',
          ROW_INVOICE_NUMBER_LABEL: 'CALCULATION.PDF.FOOTER.ADDITIONAL_EXPENSE_PART.ROW_INVOICE_NUMBER_LABEL'
        },
        DUE_DATE_PART : {
          DUE_DATE_LABEL: 'CALCULATION.PDF.FOOTER.DUE_DATE_PART.DUE_DATE_LABEL',
          FINANCE_LABEL: 'CALCULATION.PDF.FOOTER.DUE_DATE_PART.FINANCE_LABEL'
        },
      },
      HEADER: {
        HEADER: {
          SUPPLIER_INVOICE_NUM_LABEL: 'CALCULATION.PDF.HEADER.HEADER.SUPPLIER_INVOICE_NUM_LABEL',
          FROM_LABEL:  'CALCULATION.PDF.HEADER.HEADER.FROM_LABEL',
          CALCULATION_DATE_LABEL: 'CALCULATION.PDF.HEADER.HEADER.CALCULATION_DATE_LABEL',
        },
        SUPPLIER_PART: {
          TAX_NUMBER_LABEL: 'CALCULATION.PDF.HEADER.SUPPLIER_PART.TAX_NUMBER_LABEL',
          COMPANY_NUMBER_LABEL : 'CALCULATION.PDF.HEADER.SUPPLIER_PART.COMPANY_NUMBER_LABEL',
          SUPPLIER_LABEL: 'CALCULATION.PDF.HEADER.SUPPLIER_PART.SUPPLIER_LABEL',
          CUSTOMER_LABEL: 'CALCULATION.PDF.HEADER.SUPPLIER_PART.CUSTOMER_LABEL'
        }
      },
      PDF: {
        TITLE: 'CALCULATION.PDF.PDF.TITLE',
        TH_NAME_LABEL: 'CALCULATION.PDF.PDF.TH_NAME_LABEL',
        TH_INVOICE_DATA_LABEL: 'CALCULATION.PDF.PDF.INVOICE_DATA_LABEL',
        TH_EXPENSE_LABEL: 'CALCULATION.PDF.PDF.TH_EXPENSE_LABEL',
        TH_PRICE_DIFFERENCE_LABEL: 'CALCULATION.PDF.PDF.TH_PRICE_DIFFERENCE_LABEL',
        TH_FINANCE_TAX_LABEL: 'CALCULATION.PDF.PDF.TH_FINANCE_TAX_LABEL',
        TH_TOTAL_FINANCE_LABEL: 'CALCULATION.PDF.PDF.TH_TOTAL_FINANCE_LABEL',
        DIALOG_TITLE: 'CALCULATION.PDF.PDF.DIALOG_TITLE'
      }
    },
  },
  CASH_ACCOUNT:{
    PDF:{
      FOOTER:{
        FOOTER:{
          FOOTER_CELL_LABEL_PAYMENT_METHOD: 'CASH_ACCOUNT.PDF.FOOTER.FOOTER.FOOTER_CELL_LABEL_PAYMENT_METHOD',
          FOOTER_CELL_LABEL_NOTE_OF_THE_TAX: 'CASH_ACCOUNT.PDF.FOOTER.FOOTER.FOOTER_CELL_LABEL_NOTE_OF_THE_TAX'
        },
        SIGNATURE:{
          DATE_VIEW_LABEL: 'CASH_ACCOUNT.PDF.FOOTER.SIGNATURE.DATE_VIEW_LABEL',
          ONE_SIGNATURE_LABEL_ROBU_PREUZEO: 'CASH_ACCOUNT.PDF.FOOTER.SIGNATURE.ONE_SIGNATURE_LABEL_ROBU_PREUZEO:',
          ONE_SIGNATURE_LABEL_ODGOVORNO_LICE: 'CASH_ACCOUNT.PDF.FOOTER.SIGNATURE.ONE_SIGNATURE_LABEL_ODGOVORNO_LICE:'
        },
        SUMMARY_PART:{
          LABEL_FINANCE_NO_TAX: 'CASH_ACCOUNT.PDF.FOOTER.SUMMARY_PART.LABEL_FINANCE_NO_TAX',
          LABEL_DISCOUNT: 'CASH_ACCOUNT.PDF.FOOTER.SUMMARY_PART.LABEL_DISCOUNT',
          LABEL_FINANCE: 'CASH_ACCOUNT.PDF.FOOTER.SUMMARY_PART.LABEL_FINANCE',
          LABEL_FINANCE_TAX: 'CASH_ACCOUNT.PDF.FOOTER.SUMMARY_PART.LABEL_FINANCE_TAX',
          LABEL_FINANCE_TOTAL: 'CASH_ACCOUNT.PDF.FOOTER.SUMMARY_PART.LABEL_FINANCE_TOTAL'
        },
        TAX_PART:{
          CELL_VALUE_TAX: 'CASH_ACCOUNT.PDF.FOOTER.TAX_PART.CELL_VALUE_TAX',
          CELL_VALUE_FINANCE_NO_TAX: 'CASH_ACCOUNT.PDF.FOOTER.TAX_PART.CELL_VALUE_FINANCE_NO_TAX',
          CELL_VALUE_FINANCE_TAX: 'CASH_ACCOUNT.PDF.FOOTER.TAX_PART.CELL_VALUE_FINANCE_TAX',
          CELL_VALUE_FINANCE_WITH_TAX: 'CASH_ACCOUNT.PDF.FOOTER.TAX_PART.CELL_VALUE_FINANCE_WITH_TAX'
        }
      },
      HEADER:{
        HEADER:{
          VIEW_TEXT_RECEIPT_NUM:'CASH_ACCOUNT.PDF.HEADER.HEADER.VIEW_TEXT_RECEIPT_NUM',
          VIEW_LABEL_DATE: 'CASH_ACCOUNT.PDF.HEADER.HEADER.VIEW_LABEL_DATE'
        }
      },
      CASH_RECEIPT_PDF:{
        PDF_TITLE: 'CASH_ACCOUNT.PDF.CASH_RECEIPT_PDF.PDF_TITLE'
      }
    },
    CASH_RECEIPT_FORM:{
      ERROR_MESSAGE_CUSTOMER_IS_REQUIRED: 'CASH_ACCOUNT.CASH_RECEIPT_FORM.ERROR_MESSAGE_CUSTOMER_IS_REQUIRED',
      INPUT_LABEL: 'CASH_ACCOUNT.CASH_RECEIPT_FORM.INPUT_LABEL',
      INPUT_HELPER_TEXT: 'CASH_ACCOUNT.CASH_RECEIPT_FORM.INPUT_HELPER_TEXT',
      BUTTON_SHORTCUT_LABEL_CUSTOMER:'CASH_ACCOUNT.CASH_RECEIPT_FORM.BUTTON_SHORTCUT_LABEL_CUSTOMER',
      DIALOG_BUTTON_LABEL_GENERATE: 'CASH_ACCOUNT.CASH_RECEIPT_FORM.DIALOG_BUTTON_LABEL_GENERATE',
      DIALOG_CASH_RECEIPT_PDF_LABEL_RB: 'CASH_ACCOUNT.CASH_RECEIPT_FORM.DIALOG_CASH_RECEIPT_PDF_LABEL_RB',
      DIALOG_CASH_RECEIPT_PDF_LABEL_ARTICLE: 'CASH_ACCOUNT.CASH_RECEIPT_FORM.DIALOG_CASH_RECEIPT_PDF_LABEL_ARTICLE',
      DIALOG_CASH_RECEIPT_PDF_LABEL_QTY: 'CASH_ACCOUNT.CASH_RECEIPT_FORM.DIALOG_CASH_RECEIPT_PDF_LABEL_QTY',
      DIALOG_CASH_RECEIPT_PDF_LABEL_PRICE: 'CASH_ACCOUNT.CASH_RECEIPT_FORM.DIALOG_CASH_RECEIPT_PDF_LABEL_PRICE',
      DIALOG_CASH_RECEIPT_PDF_LABEL_FINANCE: 'CASH_ACCOUNT.CASH_RECEIPT_FORM.DIALOG_CASH_RECEIPT_PDF_LABEL_FINANCE',
      DIALOG_CASH_RECEIPT_PDF_LABEL_TAX_FINANCE: 'CASH_ACCOUNT.CASH_RECEIPT_FORM.DIALOG_CASH_RECEIPT_PDF_LABEL_TAX_FINANCE',
      DIALOG_CASH_RECEIPT_PDF_LABEL_INVOICE_FINANCE: 'CASH_ACCOUNT.CASH_RECEIPT_FORM.DIALOG_CASH_RECEIPT_PDF_LABEL_INVOICE_FINANCE',
      DIALOG_TITLE: 'CASH_ACCOUNT.CASH_RECEIPT_FORM.DIALOG_TITLE'
    }
  },
  CONTACT: {
    CONTACT_FORM: {
      SELECT_CONTACT_TYPE_LABEL: 'CONTACT.CONTACT_FORM.SELECT_CONTACT_TYPE_LABEL',
      SELECT_CONTACT_TYPE_HELPER_TEXT: 'CONTACT.CONTACT_FORM.SELECT_CONTACT_TYPE_HELPER_TEXT',
      INPUT_CONTACT_TYPE_EMAIL_LABEL: 'CONTACT.CONTACT_FORM.INPUT_CONTACT_TYPE_EMAIL_LABEL',
      CONTACT_HELPER_TEXT_ENTER_VALUE: 'CONTACT.CONTACT_FORM.CONTACT_HELPER_TEXT_ENTER_VALUE',
      INPUT_CONTACT_TYPE_WEB_LABEL: 'CONTACT.CONTACT_FORM.INPUT_CONTACT_TYPE_WEB_LABEL',
      INPUT_CONTACT_TYPE_PHONE_LABEL: 'CONTACT.CONTACT_FORM.INPUT_CONTACT_TYPE_PHONE_LABEL',
      INPUT_CONTACT_PHONE_VALIDATION_FORMAT_MESSAGE: 'CONTACT.CONTACT_FORM.INPUT_CONTACT_PHONE_VALIDATION_FORMAT_MESSAGE',
      INPUT_CONTACT_DESCRIPTION_LABEL: 'CONTACT.CONTACT_FORM.INPUT_CONTACT_DESCRIPTION',
      INPUT_CONTACT_DESCRIPTION_HELPER_TEXT: 'CONTACT.CONTACT_FORM.INPUT_CONTACT_DESCRIPTION_HELPER_TEXT',
      DIALOG_TITLE_INSERT: 'CONTACT.CONTACT_FORM.DIALOG_TITLE_INSERT',
      DIALOG_TITLE_EDIT: 'CONTACT.CONTACT_FORM.DIALOG_TITLE_EDIT',
      DIALOG_TITLE_DELETE: 'CONTACT.CONTACT_FORM.DIALOG_TITLE_DELETE',
      DIALOG_DELETE_CONTACT_MESSAGE: 'CONTACT.CONTACT_FORM.DIALOG_DELETE_CONTACT_MESSAGE'
    },
    CONTACT_VIEW: {
      TITLE: 'CONTACT.CONTACT_VEW.TITLE',
      BUTTON_ADD: 'CONTACT.CONTACT_VEW.BUTTON_ADD'
    }
  },
  CURRENCY:{
    CONVERT_CURRENCY_FORM:{
      LABEL: 'CURRENCY.CONVERT_CURRENCY_FORM.LABEL',
      SELECT_LABEL_FROM: 'CURRENCY.CONVERT_CURRENCY_FORM.SELECT_LABEL_FROM',
      SELECT_LABEL_TO: 'CURRENCY.CONVERT_CURRENCY_FORM.SELECT_LABEL_TO',
      INPUT_LABEL_AMOUNT:'CURRENCY.CONVERT_CURRENCY_FORM.INPUT_LABEL_AMOUNT',
      BUTTON_LABEL_CONVERT:'CURRENCY.CONVERT_CURRENCY_FORM.BUTTON_LABEL_CONVERT',
    },
    CURRENCY_DIALOG:{
      CURRENCY_CONVERTER_TITLE:'CURRENCY.CURRENCY_DIALOG.CURRENCY_CONVERTER_TITLE',
      DIALOG_CURRENCY_TITLE:'CURRENCY.CURRENCY_DIALOG.DIALOG_CURRENCY_TITLE'
    },
    CURRENCY_LIST:{
      CURRENCY_LIST_NAME:'CURRENCY.CURRENCY_LIST.CURRENCY_LIST_NAME',
      CURRENCY_LIST_SYMBOL:'CURRENCY.CURRENCY_LIST.CURRENCY_LIST_SYMBOL',
      CURRENCY_LIST_MARK:'CURRENCY.CURRENCY_LIST.CURRENCY_LIST_MARK',
      CURRENCY_LIST_BY_RATE:'CURRENCY.CURRENCY_LIST.CURRENCY_LIST_BY_RATE',
      CURRENCY_LIST_MID_RATE:'CURRENCY.CURRENCY_LIST.CURRENCY_LIST_MID_RATE',
      CURRENCY_LIST_SALE_RATE:'CURRENCY.CURRENCY_LIST.CURRENCY_LIST_SELL_RATE',

    }
  },
  CUSTOMER: {
    DASHBOARD: {
      INPUT_HELPER_TEXT: 'CUSTOMER.DASHBOARD.INPUT_HELPER_TEXT',
      TAB_INFO_LABEL: 'CUSTOMER.DASHBOARD.TAB_INFO_LABEL',
      TAB_CARD_LABEL: 'CUSTOMER.DASHBOARD.TAB_CARD_LABEL',
      TAB_PAYMENTS_LABEL: 'CUSTOMER.DASHBOARD.TAB_PAYMENTS_LABEL'
    },
    CARD: {
      PDF: {
        CUSTOMER_CARD_PDF: {
          TITLE: 'CUSTOMER.CARD.PDF.CUSTOMER_CARD_PDF.TITLE',
        },
        RENDER_COLUMN: {
          TITLE: 'CUSTOMER.CARD.PDF.RENDER_COLUMN.TITLE'
        }
      },
      VIEWS: {
        FINANCE_BALANCE_DATA: {
          OWES_LABEL: 'CUSTOMER.CARD.VIEWS.FINANCE_BALANCE_DATA.OWES_LABEL',
          CLAIMS_LABEL: 'CUSTOMER.CARD.VIEWS.FINANCE_BALANCE_DATA.CLAIMS_LABEL',
          DELAY_OWES: 'CUSTOMER.CARD.VIEWS.FINANCE_BALANCE_DATA.DELAY_OWES',
          OWES_TODAY: 'CUSTOMER.CARD.VIEWS.FINANCE_BALANCE_DATA.OWES_TODAY',
          DELAY_CLAIMS: 'CUSTOMER.CARD.VIEWS.FINANCE_BALANCE_DATA.DELAY_CLAIMS',
          CLAIMS_TODAY: 'CUSTOMER.CARD.VIEWS.FINANCE_BALANCE_DATA.CLAIMS_TODAY'
        },
        FINANCE_FUTURE_DATA: {
          OWES_LABEL: 'CUSTOMER.CARD.VIEWS.FINANCE_FUTURE_DATA.OWES_LABEL',
          CLAIMS_LABEL: 'CUSTOMER.CARD.VIEWS.FINANCE_FUTURE_DATA.CLAIMS_LABEL',
          SUMMARIZE_LABEL: 'CUSTOMER.CARD.VIEWS.FINANCE_FUTURE_DATA.SUMMARIZE_LABEL'
        }
      },
      CARD_TABLE: {
        TH_DATE_LABEL: 'CUSTOMER.CARD.CARD_TABLE.TH_DATE_LABEL',
        TH_DOCUMENT_LABEL: 'CUSTOMER.CARD.CARD_TABLE.TH_DOCUMENT_LABEL',
        TH_OWES_LABEL: 'CUSTOMER.CARD.CARD_TABLE.TH_OWES_LABEL',
        TH_CLAIMS_LABEL: 'CUSTOMER.CARD.CARD_TABLE.TH_CLAIMS_LABEL',
        TH_DUE_DATE_LABEL: 'CUSTOMER.CARD.CARD_TABLE.TH_DUE_DATE_LABEL',
        BUTTON_PRINT_LABEL: 'CUSTOMER.CARD.CARD_TABLE.BUTTON_PRINT_LABEL',
        CARD_TABLE_FILTER: {
          INPUT_DATE_PICKER_FROM_HELPER_TEXT: 'CUSTOMER.CARD.CARD_TABLE.CARD_TABLE_FILTER.INPUT_DATE_PICKER_FROM_HELPER_TEXT',
          INPUT_DATE_PICKER_TO_HELPER_TEXT: 'CUSTOMER.CARD.CARD_TABLE.CARD_TABLE_FILTER.INPUT_DATE_PICKER_TO_HELPER_TEXT',
        },
        PDF: {
          TABLE_COLUMN_DATE_LABEL: 'CUSTOMER.CARD.CARD_TABLE.PDF.TABLE_COLUMN_DATE_LABEL',
          TABLE_COLUMN_OWES_LABEL: 'CUSTOMER.CARD.CARD_TABLE.PDF.TABLE_COLUMN_OWES_LABEL',
          TABLE_COLUMN_CLAIMS_LABEL: 'CUSTOMER.CARD.CARD_TABLE.PDF.TABLE_COLUMN_CLAIMS_LABEL',
          TABLE_COLUMN_DUE_DATES_LABEL: 'CUSTOMER.CARD.CARD_TABLE.PDF.TABLE_COLUMN_DUE_DATES_LABEL',
          DIALOG_TITLE: 'CUSTOMER.CARD.CARD_TABLE.PDF.DIALOG_TITLE'
        }
      },
      CUSTOMER_FINANCE_BALANCE: {
        TITLE: 'CUSTOMER.CARD.CUSTOMER_FINANCE_BALANCE.TITLE'
      },
      CUSTOMER_FINANCE_FUTURE: {
        TITLE: 'CUSTOMER.CARD.CUSTOMER_FINANCE_FUTURE.TITLE'
      }
    }
  },

  FINANCE_TRANSFER_DOCUMENT:{
    FORM:{
      FINANCE_TRANSFER_DOCUMENT_FORM:{
        ERROR_MESSAGE_CUSTOMER: 'FINANCE_TRANSFER_DOCUMENT.FORM.FINANCE_TRANSFER_DOCUMENT_FORM.ERROR_MESSAGE_CUSTOMER',
        ERROR_MESSAGE_VALUE:'FINANCE_TRANSFER_DOCUMENT.FORM.FINANCE_TRANSFER_DOCUMENT_FORM.ERROR_MESSAGE_VALUE',
        TITLE_ADVANCE_INVOICE:'FINANCE_TRANSFER_DOCUMENT.FORM.FINANCE_TRANSFER_DOCUMENT_FORM.TITLE_ADVANCE_INVOICE',
        TITLE_FINANCE_TRANSFER_DOCUMENT:'FINANCE_TRANSFER_DOCUMENT.FORM.FINANCE_TRANSFER_DOCUMENT_FORM.TITLE_FINANCE_TRANSFER_DOCUMENT',
        BUTTON_SWITCH_LABEL:'FINANCE_TRANSFER_DOCUMENT.FORM.FINANCE_TRANSFER_DOCUMENT_FORM.BUTTON_SWITCH_LABEL',
        DATE_PICKER_HELPER_TEXT:'FINANCE_TRANSFER_DOCUMENT.FORM.FINANCE_TRANSFER_DOCUMENT_FORM.DATE_PICKER_HELPER_TEXT',
        DATE_PICKER_LABEL:'FINANCE_TRANSFER_DOCUMENT.FORM.FINANCE_TRANSFER_DOCUMENT_FORM.DATE_PICKER_LABEL',
        DATE_PICKER_VALIDATION_HELPER_TEXT:'FINANCE_TRANSFER_DOCUMENT.FORM.FINANCE_TRANSFER_DOCUMENT_FORM.DATE_PICKER_VALIDATION_HELPER_TEXT',
        DATE_PICKER_VALIDATION_LABEL:'FINANCE_TRANSFER_DOCUMENT.FORM.FINANCE_TRANSFER_DOCUMENT_FORM.DATE_PICKER_VALIDATION_LABEL',
        TEXT_AREA_LABEL:'FINANCE_TRANSFER_DOCUMENT.FORM.FINANCE_TRANSFER_DOCUMENT_FORM.TEXT_AREA_LABEL',
        TEXT_AREA_HELPER_TEXT:'FINANCE_TRANSFER_DOCUMENT.FORM.FINANCE_TRANSFER_DOCUMENT_FORM.TEXT_AREA_HELPER_TEXT',

      },
      ITEM_FINANCE_PART:{
        LABEL_TAX:'FINANCE_TRANSFER_DOCUMENT.FORM.ITEM_FINANCE_PART.LABEL_TAX',
        TEXT_AREA_LABEL:'FINANCE_TRANSFER_DOCUMENT.FORM.ITEM_FINANCE_PART.TEXT_AREA_LABEL',
        HELPER_TEXT:'FINANCE_TRANSFER_DOCUMENT.FORM.ITEM_FINANCE_PART.TEXT_AREA_LABEL',
        SELECT_HELPER_TEXT:'FINANCE_TRANSFER_DOCUMENT.FORM.ITEM_FINANCE_PART.SELECT_HELPER_TEXT',
        SELECT_LABEL:'FINANCE_TRANSFER_DOCUMENT.FORM.ITEM_FINANCE_PART.SELECT_LABEL',
        SELECT_MESSAGE:'FINANCE_TRANSFER_DOCUMENT.FORM.ITEM_FINANCE_PART.SELECT_MESSAGE',
        INPUT_TEXT_LABEL:'FINANCE_TRANSFER_DOCUMENT.FORM.ITEM_FINANCE_PART.INPUT_TEXT_LABEL',
        INPUT_TEXT_HELPER_TEXT:'FINANCE_TRANSFER_DOCUMENT.FORM.ITEM_FINANCE_PART.INPUT_TEXT_HELPER_TEXT',
        INPUT_WITH_VALIDATION_LABEL:'FINANCE_TRANSFER_DOCUMENT.FORM.ITEM_FINANCE_PART.INPUT_WITH_VALIDATION_LABEL',
        INPUT_WITH_VALIDATION_HELPER_TEXT:'FINANCE_TRANSFER_DOCUMENT.FORM.ITEM_FINANCE_PART.INPUT_WITH_VALIDATION_HELPER_TEXT',
        INPUT_WITH_VALIDATION_MESSAGE:'FINANCE_TRANSFER_DOCUMENT.FORM.ITEM_FINANCE_PART.INPUT_WITH_VALIDATION_MESSAGE',
      }
    },
    MAIN:{
      FILTER:{
        BUTTON_SHORTCUT_LABEL_CLEAR: 'FINANCE_TRANSFER_DOCUMENT.MAIN.FILTER.BUTTON_SHORTCUT_LABEL_CLEAR',
        BUTTON_SHORTCUT_LABEL_OPTION_CUSTOMER: 'FINANCE_TRANSFER_DOCUMENT.MAIN.FILTER.BUTTON_SHORTCUT_LABEL_OPTION_CUSTOMER',
        DATE_PICKER_HELPER_TEXT: 'FINANCE_TRANSFER_DOCUMENT.MAIN.FILTER.DATE_PICKER_HELPER_TEXT',
        DATE_PICKER_LABEL:'FINANCE_TRANSFER_DOCUMENT.MAIN.FILTER.DATE_PICKER_LABEL',
        DATE_PICKER_HELPER_TEXT_DATE_TO:'FINANCE_TRANSFER_DOCUMENT.MAIN.FILTER.DATE_PICKER_HELPER_TEXT_DATE_TO',
        SELECT_LABEL_IN_OUT: 'FINANCE_TRANSFER_DOCUMENT.MAIN.FILTER.SELECT_LABEL_IN_OUT',
        SELECT_LABEL_LABEL_STATUS:'FINANCE_TRANSFER_DOCUMENT.MAIN.FILTER.SELECT_LABEL_LABEL_STATUS'

      }
    },
    PDF:{
      HEADER:{
        LABEL_NUM:'FINANCE_TRANSFER_DOCUMENT.PDF.HEADER.LABEL_NUM',
        LABEL_DOCUMENT_DATE:'FINANCE_TRANSFER_DOCUMENT.PDF.HEADER.LABEL_DOCUMENT_DATE',
        LABEL_DUE_DATE:'FINANCE_TRANSFER_DOCUMENT.PDF.HEADER.LABEL_DUE_DATE'
      },
      PDF:{
        TITLE_ADVANCE_INVOICE:'FINANCE_TRANSFER_DOCUMENT.PDF.PDF.TITLE_ADVANCE_INVOICE',
        TITLE_FIN_TRANS_DOCUMENT:'FINANCE_TRANSFER_DOCUMENT.PDF.PDF.TITLE_FIN_TRANS_DOCUMENT',
        LABEL_ADVANCE_INVOICE_FINANCE:'FINANCE_TRANSFER_DOCUMENT.PDF.PDF.LABEL_ADVANCE_INVOICE_FINANCE',
        LABEL_TRANS_DOC_FINANCE:'FINANCE_TRANSFER_DOCUMENT.PDF.PDF.LABEL_TRANS_DOC_FINANCE',
      }
    },
    PREVIEW:{
      PREVIEW:{
        TITLE_ADVANCE_INVOICE:'FINANCE_TRANSFER_DOCUMENT.PREVIEW.PREVIEW.TITLE_ADVANCE_INVOICE',
        TITLE_FINANCE_TRANSFER_DOCUMENT: 'FINANCE_TRANSFER_DOCUMENT.PREVIEW.PREVIEW.TITLE_FINANCE_TRANSFER_DOCUMENT',
        LABEL_DATE: 'FINANCE_TRANSFER_DOCUMENT.PREVIEW.PREVIEW.LABEL_DATE',
        LABEL_DUE_DATE: 'FINANCE_TRANSFER_DOCUMENT.PREVIEW.PREVIEW.LABEL_DUE_DATE',
        TITLE_NOTES: 'FINANCE_TRANSFER_DOCUMENT.PREVIEW.PREVIEW.TITLE_NOTES',
        DIALOG_PREVIEW_FINANCE_TRANSFER_DOCUMENT_ADVANCE_INFORM_PREVIEW:'FINANCE_TRANSFER_DOCUMENT.PREVIEW.PREVIEW.DIALOG_PREVIEW_FINANCE_TRANSFER_DOCUMENT_ADVANCE_INFORM_PREVIEW',
        DIALOG_PREVIEW_FINANCE_TRANSFER_DOCUMENT_PREVIEW:'FINANCE_TRANSFER_DOCUMENT.PREVIEW.PREVIEW.DIALOG_PREVIEW_FINANCE_TRANSFER_DOCUMENT_FINANCE_TRANSFER_DOCUMENT_PREVIEW'
      }
    },
    FINANCE_TRANSFER_DOCUMENT:{
      LABEL_NEW_ADVANCE_INVOICE:'FINANCE_TRANSFER_DOCUMENT.FINANCE_TRANSFER_DOCUMENT.LABEL_NEW_ADVANCE_INVOICE',
      LABEL_NEW_FINANCE_TRANSFER:'FINANCE_TRANSFER_DOCUMENT.FINANCE_TRANSFER_DOCUMENT.LABEL_NEW_FINANCE_TRANSFER',
      DIALOG_CANCEL_MESSAGE: 'FINANCE_TRANSFER_DOCUMENT.FINANCE_TRANSFER_DOCUMENT.DIALOG_CANCEL_MESSAGE',
      DIALOG_CANCEL_ADVANCE_INVOICE:'FINANCE_TRANSFER_DOCUMENT.FINANCE_TRANSFER_DOCUMENT.DIALOG_CANCEL_ADVANCE_INVOICE',
      DIALOG_CANCEL_FINANCE:'FINANCE_TRANSFER_DOCUMENT.FINANCE_TRANSFER_DOCUMENT.DIALOG_CANCEL_FINANCE',
      DIALOG_CANCEL_TITLE_ADVANCE_INVOICE:'FINANCE_TRANSFER_DOCUMENT.FINANCE_TRANSFER_DOCUMENT.DIALOG_CANCEL_TITLE_ADVANCE_INVOICE',
      DIALOG_CANCEL_TITLE:'FINANCE_TRANSFER_DOCUMENT.FINANCE_TRANSFER_DOCUMENT.DIALOG_CANCEL_FINANCE_TRANSFER_DOCUMENT_TITLE'

    },

  },
  INVOICE: {
    FORM: {
      FOOTER: {
        ADDITIONAL_EXPENSE_VIEW: {
          TITLE: 'INVOICE.FORM.FOOTER.ADDITIONAL_EXPENSE_VIEW.TITLE',
          NO_ADDITIONAL_EXPENSE_MESSAGE: 'INVOICE.FORM.FOOTER.ADDITIONAL_EXPENSE_VIEW.NO_ADDITIONAL_EXPENSE_MESSAGE',
          TH_DESCRIPTION_LABEL: 'INVOICE.FORM.FOOTER.ADDITIONAL_EXPENSE_VIEW.TH_DESCRIPTION_LABEL',
          TH_BASE_FINANCE_LABEL: 'INVOICE.FORM.FOOTER.ADDITIONAL_EXPENSE_VIEW.TH_BASE_FINANCE_LABEL',
          TH_FINANCE_LABEL: 'INVOICE.FORM.FOOTER.ADDITIONAL_EXPENSE_VIEW.TH_FINANCE_LABEL'
        },
        DUE_DATE_DIALOG: {
          TITLE: 'INVOICE.FORM.FOOTER.DUE_DATE_DIALOG.TITLE',
        },
        DUE_DATE_FORM_INLINE: {
          DATE_PICKER_LABEL: 'INVOICE.FORM.FOOTER.DUE_DATE_FORM_INLINE.DATE_PICKER_LABEL',
          HELPER_TEXT_DATE_PICKER: 'INVOICE.FORM.FOOTER.DUE_DATE_FORM_INLINE.HELPER_TEXT_DATE_PICKER',
          FINANCE_LABEL: 'INVOICE.FORM.FOOTER.DUE_DATE_FORM_INLINE.FINANCE_LABEL',
          HELPER_TEXT_FINANCE: 'INVOICE.FORM.FOOTER.DUE_DATE_FORM_INLINE.HELPER_TEXT_FINANCE',
          BUTTON_ADD_LABEL: 'INVOICE.FORM.FOOTER.DUE_DATE_FORM_INLINE.BUTTON_ADD_LABEL'
        },
        DUE_DATE_VIEW: {
          TITLE: 'INVOICE.FORM.FOOTER.DUE_DATE_VIEW.TITLE',
          TOTAL_ADDED_LABEL: 'INVOICE.FORM.FOOTER.DUE_DATE_VIEW.TOTAL_ADDED_LABEL',
          TOTAL_FINANCE_LABEL: 'INVOICE.FORM.FOOTER.DUE_DATE_VIEW.TOTAL_FINANCE_LABEL',
          NO_TABLE_DATA_MESSAGE: 'INVOICE.FORM.FOOTER.DUE_DATE_VIEW.NO_TABLE_DATA_MESSAGE'
        },
        EXPENSES_FORM : {
          SELECT_TAX_LABEL: 'INVOICE.FORM.FOOTER.EXPENSES_FORM.SELECT_TAX_LABEL',
          HELPER_TEXT_SELECT_TAX: 'INVOICE.FORM.FOOTER.EXPENSES_FORM.HELPER_TEXT_SELECT_TAX',
          FINANCE_VP_LABEL: 'INVOICE.FORM.FOOTER.EXPENSES_FORM.FINANCE_VP_LABEL',
          HELPER_TEXT_FINANCE_VP: 'INVOICE.FORM.FOOTER.EXPENSES_FORM.HELPER_TEXT_FINANCE_VP',
          FINANCE_MP_LABEL: 'INVOICE.FORM.FOOTER.EXPENSES_FORM.FINANCE_MP_LABEL',
          HELPER_TEXT_FINANCE_MP: 'INVOICE.FORM.FOOTER.EXPENSES_FORM.HELPER_TEXT_FINANCE_MP',
          DESCRIPTION_LABEL: 'INVOICE.FORM.FOOTER.EXPENSES_FORM.DESCRIPTION_LABEL',
        },
        FOOTER_FORM: {
          DISCOUNT_LABEL: 'INVOICE.FORM.FOOTER.FOOTER_FORM.DISCOUNT_LABEL',
          NOTE_LABEL: 'INVOICE.FORM.FOOTER.FOOTER_FORM.NOTE_LABEL',
          DIALOG_TITLE: 'INVOICE.FORM.FOOTER.FOOTER_FORM.DIALOG_TITLE'
        },
        INVOICE_EXPENSES: {
          BUTTON_ADD_LABEL: 'INVOICE.FORM.FOOTER.INVOICE_EXPENSES.BUTTON_ADD_LABEL',
          TITLE: 'INVOICE.FORM.FOOTER.INVOICE_EXPENSES.TITLE',
          NO_TABLE_DATA_MESSAGE: 'INVOICE.FORM.FOOTER.INVOICE_EXPENSES.NO_TABLE_DATA_MESSAGE'
        }
      },
      HEADER: {
        FORM: {
          CUSTOMER_NAME_PLACEHOLDER: 'INVOICE.FORM.HEADER.FORM.CUSTOMER_NAME_PLACEHOLDER',
          BUTTON_CUSTOMER_LABEL : 'INVOICE.FORM.HEADER.FORM.BUTTON_CUSTOMER_LABEL',
          SELECT_WAREHOUSE_LABEL : 'INVOICE.FORM.HEADER.FORM.SELECT_WAREHOUSE_LABEL',
          INPUT_DISCOUNT_LABEL: 'INVOICE.FORM.HEADER.FORM.INPUT_DISCOUNT_LABEL',
          DIALOG_TITLE: 'INVOICE.FORM.HEADER.FORM.DIALOG_TITLE'
        },
        HEADER: {
          TITLE: 'INVOICE.FORM.HEADER.HEADER.TITLE',
          CUSTOMER_TOOLTIP_MESSAGE: 'INVOICE.FORM.HEADER.HEADER.CUSTOMER_TOOLTIP_MESSAGE',
          WAREHOUSE_TYPE_TOOLTIP_MESSAGE: 'INVOICE.FORM.HEADER.HEADER.WAREHOUSE_TYPE_TOOLTIP_MESSAGE',
          DUE_DATES_TOOLTIP_MESSAGE: 'INVOICE.FORM.HEADER.HEADER.DUEdATES_TOOLTIP_MESSAGE',
          ADDITIONAL_EXPENSE_TOOLTIP_MESSAGE: 'INVOICE.FORM.HEADER.HEADER.ADDITIONAL_EXPENSE_TOOLTIP_MESSAGE',
          CUSTOMER_NAME_LABEL: 'INVOICE.FORM.HEADER.HEADER.CUSTOMER_NAME_LABEL',
          CUSTOMER_NAME_PLACEHOLDER: 'INVOICE.FORM.HEADER.HEADER.CUSTOMER_NAME_PLACEHOLDER',
          WAREHOUSE_TYPE_LABEL: 'INVOICE.FORM.HEADER.HEADER.WAREHOUSE_TYPE_LABEL',
          INVOICE_NUMBER_LABEL: 'INVOICE.FORM.HEADER.HEADER.INVOICE_NUMBER_LABEL',
          INVOICE_DATE_LABEL: 'INVOICE.FORM.HEADER.HEADER.INVOICE_DATE_LABEL',
          INVOICE_DISCOUNT_LABEL: 'INVOICE.FORM.HEADER.HEADER.INVOICE_DISCOUNT_LABEL'
        },
        NUMBER_DATE: {
          INVOICE_NUMBER_LABEL: 'INVOICE.FORM.HEADER.NUMBER_DATE.INVOICE_NUMBER_LABEL',
          INVOICE_DISCOUNT_LABEL : 'INVOICE.FORM.HEADER.NUMBER_DATE.INVOICE_DISCOUNT_LABEL',
          INVOICE_DISCOUNT_TOOLTIP_MESSAGE: 'INVOICE.FORM.HEADER.NUMBER_DATE.INVOICE_DISCOUNT_TOOLTIP_MESSAGE',
          INVOICE_DATE_LABEL: 'INVOICE.FORM.HEADER.NUMBER_DATE.INVOICE_DATE_LABEL',
        }
      },
      ITEMS: {
        INSERT_FORM: {
          BUTTON_FIND_ITEM_LABEL: 'INVOICE.FORM.ITEMS.INSERT_FORM.BUTTON_FIND_ITEM_LABEL',
          CHECKBOX_USE_DEFAULT_DISCOUNT_LABEL: 'INVOICE.FORM.ITEMS.INSERT_FORM.CHECKBOX_USE_DEFAULT_DISCOUNT_LABEL',
          BUTTON_EDIT_LABEL: 'INVOICE.FORM.ITEMS.INSERT_FORM.BUTTON_EDIT_LABEL',
          INPUT_QUANTITY_LABEL: 'INVOICE.FORM.ITEMS.INSERT_FORM.INPUT_QUANTITY_LABEL',
          INPUT_SELLING_PRICE_LABEL: 'INVOICE.FORM.ITEMS.INSERT_FORM.INPUT_SELLING_PRICE_LABEL',
          INPUT_DISCOUNT_LABEL: 'INVOICE.FORM.ITEMS.INSERT_FORM.INPUT_DISCOUNT_LABEL',
          WAREHOUSE_LABEL: 'INVOICE.FORM.ITEMS.INSERT_FORM.WAREHOUSE_LABEL',
          BUTTON_ADD_LABEL: 'INVOICE.FORM.ITEMS.INSERT_FORM.BUTTON_ADD_LABEL'
        },
        TABLE: {
          TH_ITEM_NAME_LABEL: 'INVOICE.FORM.ITEMS.TABLE.TH_ITEM_NAME_LABEL',
          TH_WAREHOUSE_LABEL: 'INVOICE.FORM.ITEMS.TABLE.TH_WAREHOUSE_LABEL',
          TH_QUANTITY_LABEL: 'INVOICE.FORM.ITEMS.TABLE.TH_QUANTITY_LABEL',
          TH_PRICE_LABEL: 'INVOICE.FORM.ITEMS.TABLE.TH_PRICE_LABEL',
          TH_DISCOUNT_LABEL: 'INVOICE.FORM.ITEMS.TABLE.TH_DISCOUNT_LABEL',
          TH_BASE_FINANCE_LABEL : 'INVOICE.FORM.ITEMS.TABLE.TH_BASE_FINANCE_LABEL',
          TH_TAX_FINANCE_LABEL: 'INVOICE.FORM.ITEMS.TABLE.TH_TAX_FINANCE_LABEL',
          TH_TOTAL_FINANCE_LABEL : 'INVOICE.FORM.ITEMS.TABLE.TH_TOTAL_FINANCE_LABEL'
        }
      },
      INDEX: {
        BUTTON_HEADER_LABEL: 'INVOICE.FORM.INDEX.BUTTON_HEADER_LABEL',
        BUTTON_FOOTER_LABEL: 'INVOICE.FORM.INDEX.BUTTON_FOOTER_LABEL',
        BUTTON_DUE_DATE_LABEL: 'INVOICE.FORM.INDEX.BUTTON_DUE_DATE_LABEL',
        BUTTON_PREVIEW_LABEL: 'INVOICE.FORM.INDEX.BUTTON_PREVIEW_LABEL',
        BUTTON_PRINT_LABEL: 'INVOICE.FORM.INDEX.BUTTON_PRINT_LABEL',
        BUTTON_FINISH_LABEL: 'INVOICE.FORM.INDEX.BUTTON_FINISH_LABEL',
        DIALOG_FINISH_MESSAGE : 'INVOICE.FORM.INDEX.DIALOG_FINISH_MESSAGE',
        DIALOG_FINISH_ERROR_MESSAGE: 'INVOICE.FORM.INDEX.DIALOG_FINISH_ERROR_MESSAGE',
        DIALOG_FINISH_TITLE: 'INVOICE.FORM.INDEX.DIALOG_FINISH_TITLE'
      },
      SUMMARY: {
        TH_TAX_LABEL: 'INVOICE.FORM.SUMMARY.TH_TAX_LABEL',
        TH_BASE_FINANCE_LABEL: 'INVOICE.FORM.SUMMARY.TH_BASE_FINANCE_LABEL',
        TH_TAX_FINANCE_LABEL : 'INVOICE.FORM.SUMMARY.TH_TAX_FINANCE_LABEL',
        TH_TOTAL_FINANCE_LABEL: 'INVOICE.FORM.SUMMARY.TH_TOTAL_FINANCE_LABEL'
      }
    },
    PDF: {
      FOOTER_DIR: {
        DUE_DATE_PART: {
          DUE_DATES_LABEL: 'INVOICE.PDF.FOOTER_DIR.DUE_DATE_PART.DUE_DATES_LABEL'
        },
        SIGNATURE: {
          DATE_AND_CITY_DOCUMENT_LABEL: 'INVOICE.PDF.FOOTER_DIR.SIGNATURE.DATE_AND_CITY_DOCUMENT_LABEL',
          GOODS_INVOICE_LABEL: 'INVOICE.PDF.FOOTER_DIR.SIGNATURE.GOODS_INVOICE_LABEL',
          INVOICE_ISSUED_LABEL: 'INVOICE.PDF.FOOTER_DIR.SIGNATURE.INVOICE_ISSUED_LABEL'
        },
        TAX_PART: {
          TH_TAX_PERCENT_LABEL: 'INVOICE.PDF.FOOTER_DIR.TAX_PART.TH_TAX_PERCENT_LABEL',
          TH_BASE_FINANCE_LABEL: 'INVOICE.PDF.FOOTER_DIR.TAX_PART.TH_BASE_FINANCE_LABEL',
          TH_TAX_FINANCE_LABEL: 'INVOICE.PDF.FOOTER_DIR.TAX_PART.TH_TAX_FINANCE_LABEL',
          TH_TOTAL_FINANCE_LABEL: 'INVOICE.PDF.FOOTER_DIR.TAX_PART.TH_TOTAL_FINANCE_LABEL',
        }
      },
      HEADER: {
        CLIENT_DATA: {
          NAME_LABEL: 'INVOICE.PDF.HEADER.CLIENT_DATA.NAME_LABEL',
          ADDRESS_LABEL: 'INVOICE.PDF.HEADER.CLIENT_DATA.ADDRESS_LABEL',
          PHONE_LABEL: 'INVOICE.PDF.HEADER.CLIENT_DATA.PHONE_LABEL',
          EMAIL_LABEL: 'INVOICE.PDF.HEADER.CLIENT_DATA.EMAIL_LABEL',
          TAX_NUMBER_LABEL: 'INVOICE.PDF.HEADER.CLIENT_DATA.TAX_NUMBER_LABEL',
          COMPANY_NUMBER_LABEL: 'INVOICE.PDF.HEADER.CLIENT_DATA.COMPANY_NUMBER_LABEL',
          BANK_ACCOUNT_LABEL: 'INVOICE.PDF.HEADER.CLIENT_DATA.BANK_ACCOUNT_LABEL'
        },
        CUSTOMER_PART: {
          TAX_NUMBER_LABEL: 'INVOICE.PDF.HEADER.CUSTOMER_PART.TAX_NUMBER_LABEL',
          COMPANY_NUMBER_LABEL: 'INVOICE.PDF.HEADER.CUSTOMER_PART.COMPANY_NUMBER_LABEL',
        },
        HEADER: {
          NUM_LABEL: 'INVOICE.PDF.HEADER.HEADER.NUM_LABEL',
          DOCUMENT_DATE_LABEL: 'INVOICE.PDF.HEADER.HEADER.DOCUMENT_DATE_LABEL'
        }
      },
      FOOTER: {
        TH_NAME_LABEL: 'INVOICE.PDF.FOOTER.TH_NAME_LABEL',
        TH_BASE_FINANCE_LABEL: 'INVOICE.PDF.FOOTER.TH_BASE_FINANCE_LABEL',
        TH_TAX_FINANCE_LABEL: 'INVOICE.PDF.FOOTER.TH_TAX_FINANCE_LABEL',
        TH_TOTAL_FINANCE_LABEL: 'INVOICE.PDF.FOOTER.TH_TOTAL_FINANCE_LABEL',
        ADDITIONAL_EXPENSE_LABEL: 'INVOICE.PDF.FOOTER.ADDITIONAL_EXPENSE_LABEL',
        NOTE_OF_TAX_EXEMPTION_LABEL: 'INVOICE.PDF.FOOTER.NOTE_OF_TAX_EXEMPTION_LABEL',
        NOTE_LABEL: 'INVOICE.PDF.FOOTER.NOTE_LABEL'
      },
      PDF: {
        TH_CODE_LABEL: 'INVOICE.PDF.PDF.TH_CODE_LABEL',
        TH_NAME_LABEL: 'INVOICE.PDF.PDF.TH_NAME_LABEL',
        TH_QTY_LABEL: 'INVOICE.PDF.PDF.TH_QTY_LABEL',
        TH_PRICE_LABEL: 'INVOICE.PDF.PDF.TH_PRICE_LABEL',
        TH_DISCOUNT_LABEL: 'INVOICE.PDF.PDF.TH_DISCOUNT_LABEL',
        TH_FINAL_PRICE_LABEL: 'INVOICE.PDF.PDF.TH_FINAL_PRICE_LABEL',
        TH_BASE_FINANCE_LABEL: 'INVOICE.PDF.PDF.TH_BASE_FINANCE_LABEL',
        TH_TAX_FINANCE_LABEL: 'INVOICE.PDF.PDF.TH_TAX_FINANCE_LABEL',
        TH_TOTAL_FINANCE_LABEL: 'INVOICE.PDF.PDF.TH_TOTAL_FINANCE_LABEL',
        DIALOG_TITLE: 'INVOICE.PDF.PDF.DIALOG_TITLE'
      }
    },
    PREVIEW: {
      NO_TABLE_DATA_MESSAGE: 'INVOICE.PREVIEW.NO_TABLE_DATA_MESSAGE',
      DIALOG_TITLE: 'INVOICE.PREVIEW.DIALOG_TITLE'
    },
    VIEWS: {
      FILTER: {
        BUTTON_CLEAR_LABEL: 'INVOICE.VIEWS.FILTER.BUTTON_CLEAR_LABEL',
        BUTTON_CUSTOMER_LABEL: 'INVOICE.VIEWS.FILTER.BUTTON_CUSTOMER_LABEL',
        DATE_FROM_HELPER_TEXT: 'INVOICE.VIEWS.FILTER.DATE_FROM_HELPER_TEXT',
        DATE_TO_HELPER_TEXT: 'INVOICE.VIEWS.FILTER.DATE_TO_HELPER_TEXT',
        STATUS_LABEL: 'INVOICE.VIEWS.FILTER.STATUS_LABEL'
      },
      MAIN_VIEW: {
        BUTTON_ADD_LABEL: 'INVOICE.VIEWS.MAIN_VIEW.BUTTON_ADD_LABEL',
        TH_DATE_LABEL: 'INVOICE.VIEWS.MAIN_VIEW.TH_DATE_LABEL',
        TH_INVOICE_NUMBER_LABEL: 'INVOICE.VIEWS.MAIN_VIEW.TH_INVOICE_NUMBER_LABEL',
        TH_CUSTOMER_NAME_LABEL: 'INVOICE.VIEWS.MAIN_VIEW.TH_CUSTOMER_NAME_LABEL',
        TH_BASE_FINANCE_LABEL: 'INVOICE.VIEWS.MAIN_VIEW.TH_BASE_FINANCE_LABEL',
        TH_TAX_FINANCE_LABEL: 'INVOICE.VIEWS.MAIN_VIEW.TH_TAX_FINANCE_LABEL',
        TH_TOTAL_FINANCE_LABEL: 'INVOICE.VIEWS.MAIN_VIEW.TH_TOTAL_FINANCE_LABEL',
        TH_STATUS_LABEL : 'INVOICE.VIEWS.MAIN_VIEW.TH_STATUS_LABEL',
        TITLE: 'INVOICE.VIEWS.MAIN_VIEW.TITLE',
        DIALOG_TITLE_CANCEL: 'INVOICE.VIEWS.MAIN_VIEW.DIALOG_TITLE_CANCEL',
        DIALOG_CANCEL_MESSAGE : 'INVOICE.VIEWS.MAIN_VIEW.DIALOG_CANCEL_MESSAGE',
      }
    }
  },
  ITEMS: {
    AUTOCOMPLETE: {
      ITEM_DESCRIPTION_LABEL: 'ITEM.AUTOCOMPLETE.ITEM_DESCRIPTION_LABEL',
      ITEM_BARCODE_LABEL: 'ITEM.AUTOCOMPLETE.ITEM_BARCODE_LABEL',
      ITEM_CODE_LABEL: 'ITEM.AUTOCOMPLETE.ITEM_CODE_LABEL',
      ITEM_PRICE_LABEL: 'ITEM.AUTOCOMPLETE.ITEM_PRICE_LABEL',
      ITEM_TAX_LABEL: 'ITEM.AUTOCOMPLETE.ITEM_TAX_LABEL'
    },
    FORM: {
      ITEM_FORM: {
        BARCODE_LABEL: 'ITEM.FORM.ITEM_FORM.BARCODE_LABEL',
        HELPER_TEXT_BARCODE: 'ITEM.FORM.ITEM_FORM.HELPER_TEXT_BARCODE',
        CODE_LABEL: 'ITEM.FORM.ITEM_FORM.CODE_LABEL',
        HELPER_TEXT_CODE: 'ITEM.FORM.ITEM_FORM.HELPER_TEXT_CODE',
        FULL_NAME_LABEL: 'ITEM.FORM.ITEM_FORM.FULL_NAME_LABEL',
        HELPER_TEXT_FULL_NAME: 'ITEM.FORM.ITEM_FORM.HELPER_TEXT_FULL_NAME',
        SHORT_NAME_LABEL: 'ITEM.FORM.ITEM_FORM.SHORT_NAME_LABEL',
        HELPER_TEXT_SHORT_NAME: 'ITEM.FORM.ITEM_FORM.HELPER_TEXT_SHORT_NAME',
        TAX_LABEL: 'ITEM.FORM.ITEM_FORM.TAX_LABEL',
        HELPER_TEXT_TAX: 'ITEM.FORM.ITEM_FORM.HELPER_TEXT_TAX',
        WHOLESALE_PRICE_LABEL: 'ITEM.FORM.ITEM_FORM.WHOLESALE_PRICE_LABEL',
        HELPER_TEXT_WHOLESALE_PRICE: 'ITEM.FORM.ITEM_FORM.HELPER_TEXT_WHOLESALE_PRICE',
        RETAIL_PRICE_LABEL: 'ITEM.FORM.ITEM_FORM.RETAIL_PRICE_LABEL',
        HELPER_TEXT_RETAIL_PRICE: 'ITEM.FORM.ITEM_FORM.HELPER_TEXT_RETAIL_PRICE',
        UNIT_OF_MEASURE_LABEL: 'ITEM.FORM.ITEM_FORM.UNIT_OF_MEASURE_LABEL',
        HELPER_TEXT_UNIT_OF_MEASURE: 'ITEM.FORM.ITEM_FORM.HELPER_TEXT_UNIT_OF_MEASURE',
        SUPPLIER_NAME_LABEL: 'ITEM.FORM.ITEM_FORM.SUPPLIER_NAME_LABEL',
        SUPPLIER_FULL_NAME_LABEL: 'ITEM.FORM.ITEM_FORM.SUPPLIER_FULL_NAME_LABEL',
        SUPPLIER_TAX_ID_LABEL: 'ITEM.FORM.ITEM_FORM.SUPPLIER_TAX_ID_LABEL',
        SUPPLIER_COMPANY_NUMBER_LABEL: 'ITEM.FORM.ITEM_FORM.SUPPLIER_COMPANY_NUMBER_LABEL',
        SUPPLIER_BARCODE_LABEL: 'ITEM.FORM.ITEM_FORM.SUPPLIER_BARCODE_LABEL',
        HELPER_TEXT_SUPPLIER_BARCODE:  'ITEM.FORM.ITEM_FORM.HELPER_TEXT_SUPPLIER_BARCODE',
        SUPPLIER_CODE_LABEL: 'ITEM.FORM.ITEM_FORM.SUPPLIER_CODE_LABEL',
        HELPER_TEXT_SUPPLIER_CODE: 'ITEM.FORM.ITEM_FORM.HELPER_TEXT_SUPPLIER_CODE',
        DIALOG_TITLE_INSERT: 'ITEM.FORM.ITEM_FORM.DIALOG_TITLE_INSERT',
        DIALOG_TITLE_EDIT: 'ITEM.FORM.ITEM_FORM.DIALOG_TITLE_EDIT'
      },
      ITEM_PRICE_TAX: {
        ITEM_NAME_LABEL: 'ITEM.FORM.ITEM_PRICE_TAX.ITEM_NAME_LABEL',
        WHOLESALE_PRICE_LABEL : 'ITEM.FORM.ITEM_PRICE_TAX.WHOLESALE_PRICE_LABEL',
        HELPER_TEXT_WHOLESALE_PRICE : 'ITEM.FORM.ITEM_PRICE_TAX.HELPER_TEXT_WHOLESALE_PRICE',
        RETAIL_PRICE_LABEL : 'ITEM.FORM.ITEM_PRICE_TAX.RETAIL_PRICE_LABEL',
        HELPER_TEXT_RETAIL_PRICE : 'ITEM.FORM.ITEM_PRICE_TAX.HELPER_TEXT_RETAIL_PRICE',
        DIALOG_TITLE_EDIT: 'ITEM.FORM.ITEM_PRICE_TAX.DIALOG_TITLE_EDIT'
      },
      ITEM_SUPPLIER: {
        SUPPLIER_LABEL: 'ITEM.FORM.ITEM_SUPPLIER.SUPPLIER_LABEL',
        HELPER_TEXT_SUPPLIER: 'ITEM.FORM.ITEM_SUPPLIER.HELPER_TEXT_SUPPLIER',
        CODE_LABEL : 'ITEM.FORM.ITEM_SUPPLIER.CODE_LABEL',
        HELPER_TEXT_CODE: 'ITEM.FORM.ITEM_SUPPLIER.HELPER_TEXT_CODE',
        DIALOG_TITLE_INSERT: 'ITEM.FORM.ITEM_SUPPLIER.DIALOG_TITLE_INSERT',
        DIALOG_TITLE_EDIT: 'ITEM.FORM.ITEM_SUPPLIER.DIALOG_TITLE_EDIT',
        DIALOG_TITLE_DELETE: 'ITEM.FORM.ITEM_SUPPLIER.DIALOG_TITLE_DELETE',
        DIALOG_DELETE_MESSAGE: 'ITEM.FORM.ITEM_SUPPLIER.DIALOG_DELETE_MESSAGE'
      }
    },
    INFO: {
      GENERAL_DETAILS: {
        GENERAL_DETAILS_LABEL: 'ITEMS.INFO.GENERAL_DETAILS.GENERAL_DETAILS_LABEL',
        BUTTON_EDIT_LABEL: 'ITEMS.INFO.GENERAL_DETAILS.BUTTON_EDIT_LABEL',
        SHORT_NAME_LABEL: 'ITEMS.INFO.GENERAL_DETAILS.SHORT_NAME_LABEL',
        FULL_NAME_LABEL: 'ITEMS.INFO.GENERAL_DETAILS.FULL_NAME_LABEL',
        BARCODE_LABEL : 'ITEMS.INFO.GENERAL_DETAILS.BARCODE_LABEL',
        CODE_LABEL: 'ITEMS.INFO.GENERAL_DETAILS.CODE_LABEL',
        WHOLESALE_PRICE_LABEL: 'ITEMS.INFO.GENERAL_DETAILS.WHOLESALE_PRICE_LABEL',
        RETAIL_PRICE_LABEL: 'ITEMS.INFO.GENERAL_DETAILS.RETAIL_PRICE_LABEL',
        TAX_LABEL : 'ITEMS.INFO.GENERAL_DETAILS.TAX_LABEL',
        PURCHASE_PRICE_LABEL: 'ITEMS.INFO.GENERAL_DETAILS.PURCHASE_PRICE_LABEL',
        BUTTON_SHOW_HISTORY_LABEL: 'ITEMS.INFO.GENERAL_DETAILS.BUTTON_SHOW_HISTORY_LABEL'
      },
      ITEM_PURCHASE_PRICE_TABLE: {
        DIALOG_TITLE: 'ITEMS.INFO.ITEM_PURCHASE_PRICE_TABLE.DIALOG_TITLE'
      },
      ITEM_WAREHOUSE_TABLE: {
        TH_WAREHOUSE_LABEL: 'ITEMS.INFO.ITEM_WAREHOUSE_TABLE.TH_WAREHOUSE_LABEL',
        TH_QTY_LABEL: 'ITEMS.INFO.ITEM_WAREHOUSE_TABLE.TH_QTY_LABEL',
        TH_FINANCE_STACK_LABEL: 'ITEMS.INFO.ITEM_WAREHOUSE_TABLE.TH_FINANCE_STACK_LABEL',
        TH_QTY_TOTAL_OWES_LABEL: 'ITEMS.INFO.ITEM_WAREHOUSE_TABLE.TH_QTY_TOTAL_OWES_LABEL',
        TH_QTY_TOTAL_CLAIMS_LABEL: 'ITEMS.INFO.ITEM_WAREHOUSE_TABLE.TH_QTY_TOTAL_CLAIMS_LABEL',
        TH_FINANCE_TOTAL_OWES_LABEL: 'ITEMS.INFO.ITEM_WAREHOUSE_TABLE.TH_FINANCE_TOTAL_OWES_LABEL',
        TH_FINANCE_TOTAL_CLAIMS_LABEL: 'ITEMS.INFO.ITEM_WAREHOUSE_TABLE.TH_FINANCE_TOTAL_CLAIMS_LABEL'
      },
      PURCHASE_PRICE_TABLE: {
        TH_SUPPLIER_LABEL: 'ITEMS.INFO.PURCHASE_PRICE_TABLE.TH_SUPPLIER_LABEL',
        TH_PRICE_LABEL: 'ITEMS.INFO.PURCHASE_PRICE_TABLE.TH_PRICE_LABEL',
        TH_DATE_LABEL: 'ITEMS.INFO.PURCHASE_PRICE_TABLE.TH_DATE_LABEL',
        TH_DOCUMENT_LABEL : 'ITEMS.INFO.PURCHASE_PRICE_TABLE.TH_DOCUMENT_LABEL',
      },
      SUPPLIER_CODE: {
        TITLE: 'ITEMS.INFO.SUPPLIER_CODE.TITLE',
        BUTTON_ADD_LABEL: 'ITEMS.INFO.SUPPLIER_CODE.BUTTON_ADD_LABEL',
        SHORT_NAME_LABEL: 'ITEMS.INFO.SUPPLIER_CODE.SHORT_NAME_LABEL',
        FULL_NAME_LABEL: 'ITEMS.INFO.SUPPLIER_CODE.FULL_NAME_LABEL',
        CODE_LABEL: 'ITEMS.INFO.SUPPLIER_CODE.CODE_LABEL'
      }
    },
    STATISTIC: {
      SALE: {
        ITEM_STATISTIC_BETWEEN_DATES: {
          TITLE: 'ITEMS.STATISTIC.SALE.ITEM_STATISTIC_BETWEEN_DATES.TITLE',
          DATE_FROM_HELPER_TEXT: 'ITEMS.STATISTIC.SALE.ITEM_STATISTIC_BETWEEN_DATES.DATE_FROM_HELPER_TEXT',
          DATE_TO_HELPER_TEXT: 'ITEMS.STATISTIC.SALE.ITEM_STATISTIC_BETWEEN_DATES.DATE_TO_HELPER_TEXT',
          NO_TABLE_DATA_MESSAGE: 'ITEMS.STATISTIC.SALE.ITEM_STATISTIC_BETWEEN_DATES.NO_TABLE_DATA_MESSAGE',
        },
        ITEM_STATISTIC_MONTH: {
          TITLE: 'ITEMS.STATISTIC.SALE.ITEM_STATISTIC_MONTH.TITLE',
          MONTH_LABEL: 'ITEMS.STATISTIC.SALE.ITEM_STATISTIC_MONTH.MONTH_LABEL',
          QUANTITY_LABEL: 'ITEMS.STATISTIC.SALE.ITEM_STATISTIC_MONTH.QUANTITY_LABEL',
          FINANCE_LABEL: 'ITEMS.STATISTIC.SALE.ITEM_STATISTIC_MONTH.FINANCE_LABEL'
        },
        ITEM_STATISTIC_TODAY: {
          TITLE: 'ITEMS.STATISTIC.SALE.ITEM_STATISTIC_TODAY.TITLE',
          QUANTITY_LABEL: 'ITEMS.STATISTIC.SALE.ITEM_STATISTIC_TODAY.QUANTITY_LABEL',
          FINANCE_LABEL: 'ITEMS.STATISTIC.SALE.ITEM_STATISTIC_TODAY.FINANCE_LABEL'
        }
      }
    },
    VIEW: {
      ITEM_SHORT_VIEW: {
        SHORT_NAME_LABEL:'ITEMS.VIEW.ITEM_SHORT_VIEW.SHORT_NAME_LABEL',
        FULL_NAME_LABEL: 'ITEMS.VIEW.ITEM_SHORT_VIEW.FULL_NAME_LABEL',
        BARCODE_LABEL: 'ITEMS.VIEW.ITEM_SHORT_VIEW.BARCODE_LABEL',
        CODE_LABEL: 'ITEMS.VIEW.ITEM_SHORT_VIEW.CODE_LABEL'
      },
      ITEM_VIEW: {
        ITEM_NAME_LABEL: 'ITEMS.VIEW.ITEM_VIEW.ITEM_NAME_LABEL',
        BARCODE_LABEL: 'ITEMS.VIEW.ITEM_VIEW.BARCODE_LABEL',
        CODE_LABEL: 'ITEMS.VIEW.ITEM_VIEW.CODE_LABEL'
      }
    }
  },

  NORMATIVE:{
    ITEMS:{
      ITEM_FORM:{
        INSERT_ITEM_ERROR:'NORMATIVE.ITEMS.ITEM_FORM.INSERT_ITEM_ERROR',
        BUTTON_SHORTCUT_LABEL:'NORMATIVE.ITEMS.ITEM_FORM.BUTTON_SHORTCUT_LABEL',
        TITLE_NO_NORMATIVE:'NORMATIVE.ITEMS.ITEM_FORM.TITLE_NO_NORMATIVE',
        SELECT_LABEL:'NORMATIVE.ITEMS.ITEM_FORM.SELECT_LABEL',
        SELECT_MESSAGE:'NORMATIVE.ITEMS.ITEM_FORM.SELECT_MESSAGE',
        INPUT_LABEL:'NORMATIVE.ITEMS.ITEM_FORM.INPUT_LABEL',
        BUTTON_SHORTCUT_SMALL_BUTTON_LABEL:'NORMATIVE.ITEMS.ITEM_FORM.BUTTON_SHORTCUT_SMALL_BUTTON_LABEL'

      },
      TABLE:{
        LABEL_ITEMS_PRICE:'NORMATIVE.ITEMS.TABLE.LABEL_ITEMS_PRICE',
        LABEL_QUANTITY:'NORMATIVE.ITEMS.TABLE.LABEL_QUANTITY'
      }
    },
    PDF:{
      PDF:{
        PDF_TITLE:'NORMATIVE.PDF.PDF.PDF_TITLE',
        PDF_COLUMN_LABEL_CODE:'NORMATIVE.PDF.PDF.PDF_COLUMN_LABEL_CODE',
        PDF_COLUMN_LABEL_NAME:'NORMATIVE.PDF.PDF.PDF_COLUMN_LABEL_NAME',
        PDF_COLUMN_LABEL_QUANTITY:'NORMATIVE.PDF.PDF.PDF_COLUMN_LABEL_QUANTITY',
        PDF_DIALOG_TITLE:'NORMATIVE.PDF.PDF.PDF_DIALOG_TITLE'

      },
      PDF_ITEM_INFO:{
        LABEL_BARCODE:'NORMATIVE.PDF.PDF_ITEM_INFO.LABEL_BARCODE',
        LABEL_CODE:'NORMATIVE.PDF.PDF_ITEM_INFO.LABEL_CODE',

      }
    },
    PREVIEW:{
      NORMATIVE_PREVIEW:{
        DIALOG_PREVIEW_NORMATIVE_TITLE:'NORMATIVE.PREVIEW.NORMATIVE_PREVIEW.DIALOG_PREVIEW_NORMATIVE_TITLE',
      }
    },
    VIEW:{
      ITEM_INFO:{
        ITEM_INFO_PLACEHOLDER_SHORT_NAME:'NORMATIVE.VIEW.ITEM_INFO_PLACEHOLDER_SHORT_NAME',
        ITEM_INFO_LABEL_BARCODE:'NORMATIVE.VIEW.ITEM_INFO.ITEM_INFO_LABEL_BARCODE',
        ITEM_INFO_LABEL_ITEMS_WHOLESALE_PRICE:'NORMATIVE.VIEW.ITEM_INFO.ITEM_INFO_LABEL_ITEMS_WHOLESALE_PRICE'

      },
      NORMS_TABLE:{
        TABLE_HEADER_LABEL:'NORMATIVE.VIEW.NORMS_TABLE.TABLE_HEADER_LABEL',
        DIALOG_DELETE_NORMATIVE_MESSAGE:'NORMATIVE.VIEW.NORMS_TABLE.DIALOG_DELETE_NORMATIVE_MESSAGE',
        DIALOG_TITLE_DELETE_NORMATIVE:'NORMATIVE.VIEW.NORMS_TABLE.DIALOG_TITLE_DELETE_NORMATIVE'
      }
    },
    DASHBOARD:{
      LABEL_ADD:'NORMATIVE.DASHBOARD.LABEL_ADD',
      LABEL_SUMMARIZE:'NORMATIVE.DASHBOARD.LABEL_SUMMARIZE',
      SEARCH_VIEW_HELPER_TEXT:'NORMATIVE.DASHBOARD.SEARCH_VIEW_HELPER_TEXT'
    },
    FORM:{
      INPUT_TEXT_VALIDATION_MESSAGE:'NORMATIVE.FORM.INPUT_TEXT_VALIDATION_MESSAGE',
      INPUT_TEXT_LABEL_FINANCE_VP: 'NORMATIVE.FORM.INPUT_TEXT_LABEL',
      INPUT_TEXT_REQUIRED_FIELD:'NORMATIVE.FORM.INPUT_TEXT_REQUIRED_FIELD',
      INPUT_TEXT_LABEL_DESCRIPTION:'NORMATIVE.FORM.INPUT_TEXT_LABEL_DESCRIPTION',
      DIALOG_NORMATIVE_FORM_TITLE_EDIT_NORMATIVE:'NORMATIVE.FORM.DIALOG_NORMATIVE_FORM_TITLE_EDIT_NORMATIVE',
      DIALOG_NORMATIVE_FORM_TITLE_DEFINE_NEW_NORMATIVE:'NORMATIVE.FORM.DIALOG_NORMATIVE_FORM_TITLE_DEFINE_NEW_NORMATIVE'
    }
  },
  PRODUCTION_ORDER:{
    PREVIEW:{
      PREVIEW:{
        PRODUCTION_ORDER_MESSAGE:'PRODUCTION_ORDER.PREVIEW.PREVIEW.PRODUCTION_ORDER_MESSAGE',
        DIALOG_PREVIEW_PRODUCTION_ORDER_TITLE:'PRODUCTION_ORDER.PREVIEW.PREVIEW.DIALOG_PREVIEW_PRODUCTION_ORDER_TITLE'
      }
    },
    VIEWS:{
      INSTANCE:{
        HEADER:{
          FORM:{
            SELECT_TEXT_LABEL:'PRODUCTION_ORDER.VIEWS.INSTANCE.HEADER.FORM.SELECT_TEXT_LABEL',
            INPUT_TEXT_MESSAGE:'PRODUCTION_ORDER.VIEWS.INSTANCE.HEADER.FORM.INPUT_TEXT_MESSAGE',
            INPUT_TEXT_LABEL_QUANTITY: 'PRODUCTION_ORDER.VIEWS.INSTANCE.HEADER.INPUT_TEXT_LABEL_QUANTITY',
            DATE_PICKER_LABEL:'PRODUCTION_ORDER.VIEWS.INSTANCE.HEADER.DATE_PICKER_LABEL',
            DIALOG_PRODUCTION_ORDER_HEADER_FORM_TITLE:'PRODUCTION_ORDER.VIEWS.INSTANCE.DIALOG_PRODUCTION_ORDER_HEADER_FORM_TITLE',
          },
          HEADER:{
            PRODUCTION_ORDER_HEADER_LABEL_NUMBER:'PRODUCTION_ORDER.VIEWS.INSTANCE.HEADER.HEADER.PRODUCTION_ORDER_HEADER_TEXT_NUMBER',
            PRODUCTION_ORDER_HEADER_PLACEHOLDER_NUMBER:'PRODUCTION_ORDER.VIEWS.INSTANCE.HEADER.HEADER.PRODUCTION_ORDER_HEADER_PLACEHOLDER_NUMBER',
            PRODUCTION_ORDER_HEADER_LABEL_INVOICE_DATE: 'PRODUCTION_ORDER.VIEWS.INSTANCE.HEADER.HEADER.PRODUCTION_ORDER_HEADER_TEXT_INVOICE_DATE',
            PRODUCTION_ORDER_HEADER_MESSAGE_PRODUCTION_ORDER_DATE: 'PRODUCTION_ORDER.VIEWS.INSTANCE.HEADER.HEADER.PRODUCTION_ORDER_HEADER_MESSAGE_PRODUCTION_ORDER_DATE',
            PRODUCTION_ORDER_HEADER_LABEL_ITEM_NAME:'PRODUCTION_ORDER.VIEWS.INSTANCE.HEADER.HEADER.PRODUCTION_ORDER_HEADER_LABEL_ITEM_NAME',
            PRODUCTION_ORDER_HEADER_PLACEHOLDER_ITEM_NAME:'PRODUCTION_ORDER.VIEWS.INSTANCE.HEADER.HEADER.PRODUCTION_ORDER_HEADER_PLACEHOLDER_ITEM_NAME',
            PRODUCTION_ORDER_HEADER_LABEL_NORMATIVE:'PRODUCTION_ORDER.VIEWS.INSTANCE.HEADER.HEADER.PRODUCTION_ORDER_HEADER_LABEL_NORMATIVE',
            PRODUCTION_ORDER_HEADER_PLACEHOLDER_NORMATIVE:'PRODUCTION_ORDER.VIEWS.INSTANCE.HEADER.HEADER.PRODUCTION_ORDER_HEADER_PLACEHOLDER_NORMATIVE',
            PRODUCTION_ORDER_HEADER_LABEL_QUANTITY:'PRODUCTION_ORDER.VIEWS.INSTANCE.HEADER.HEADER.PRODUCTION_ORDER_HEADER_LABEL_QUANTITY',

          }
        },
        ITEMS:{
          INSERT_FORM:{
            PRODUCTION_ORDER_ITEM_FORM_INSERT_ITEM_REQUIRED_FIELD:'PRODUCTION_ORDER.VIEWS.INSTANCE.ITEMS.INSERT_FORM.PRODUCTION_ORDER_ITEM_FORM_INSERT_ITEM_REQUIRED_FIELD',
            BUTTON_SHORTCUT_LABEL_WAREHOUSE: 'PRODUCTION_ORDER.VIEWS.INSTANCE.ITEMS.INSERT_FORM.BUTTON_SHORTCUT_LABEL',
            INPUT_TEXT_LABEL_QTY:'PRODUCTION_ORDER.VIEWS.INSTANCE.ITEMS.INSERT_FORM.INPUT_TEXT_LABEL_QTY',
            BUTTON_SHORTCUT_LABEL_ADD: 'PRODUCTION_ORDER.VIEWS.INSTANCE.ITEMS.INSERT_FORM.BUTTON_SHORTCUT_LABEL_ADD',

          }
        },
        PRODUCTION_FORM:{
          APP_BAR_BUTTONS_LABEL_HEADER:'PRODUCTION_ORDER.VIEWS.INSTANCE.PRODUCTION_FORM.APP_BAR_BUTTONS_LABEL_HEADER',
          APP_BAR_BUTTONS_LABEL_PREVIEW:'PRODUCTION_ORDER.VIEWS.INSTANCE.PRODUCTION_FORM.APP_BAR_BUTTONS_LABEL_PREVIEW',
          APP_BAR_BUTTONS_LABEL_PRINT:'PRODUCTION_ORDER.VIEWS.INSTANCE.PRODUCTION_FORM.APP_BAR_BUTTONS_LABEL_PRINT',

        }
      },
      MAIN:{
        FILTER:{
          HELPER_TEXT_DATE_TO:'PRODUCTION_ORDER.VIEWS.MAIN.FILTER.HELPER_TEXT_DATE_TO',
          HELPER_TEXT_DATE_FROM:'PRODUCTION_ORDER.VIEWS.MAIN.FILTER.HELPER_TEXT_DATE_FROM',
          SELECT_LABEL:'PRODUCTION_ORDER.VIEWS.MAIN.FILTER.SELECT_LABEL'
        }
      }
    }
  },

  PROFORMA_INVOICE:{
    PDF:{
      PDF:{
        PDF_TITLE:'PROFORMA_INVOICE.PDF.PDF.PDF_TITLE',
        LABEL_CODE:'PROFORMA_INVOICE.PDF.PDF.LABEL_CODE',
        LABEL_NAME:'PROFORMA_INVOICE.PDF.PDF.LABEL_NAME',
        LABEL_QUANTITY:'PROFORMA_INVOICE.PDF.PDF.LABEL_QUANTITY',
        LABEL_PRICE:'PROFORMA_INVOICE.PDF.PDF.LABEL_PRICE',
        LABEL_DISCOUNT:'PROFORMA_INVOICE.PDF.PDF.LABEL_DISCOUNT',
        LABEL_FINALE_PRICE:'PROFORMA_INVOICE.PDF.PDF.LABEL_FINALE_PRICE',
        LABEL_FINANCE_NO_TAX: 'PROFORMA_INVOICE.PDF.PDF.LABEL_FINANCE_NO_TAX',
        LABEL_TAX_FINANCE: 'PROFORMA_INVOICE.PDF.PDF.LABEL_TAX_FINANCE',
        LABEL_TOTAL:'PROFORMA_INVOICE.PDF.PDF.LABEL_TOTAL',
        DIALOG_TITLE:'PROFORMA_INVOICE.PDF.PDF.DIALOG_TITLE',

      }
    },
    PREVIEW:{
      PREVIEW:{
        INVOICE_MESSAGE:'PROFORMA_INVOICE.PREVIEW.PREVIEW.INVOICE_MESSAGE',
        DIALOG_TITLE:'PROFORMA_INVOICE.PREVIEW.PREVIEW.DIALOG_TITLE',
      }
    },
    VIEW:{
      INSTANCE_VIEW:{
        FOOTER:{
          FOOTER_FORM:{
            INPUT_LABEL:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.FOOTER.FOOTER_FORM.INPUT_LABEL',
            INPUT_MESSAGE: 'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.FOOTER.FOOTER_FORM.INPUT_MESSAGE',
            TEXT_AREA_LABEL:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.FOOTER.FOOTER_FORM.TEXT_AREA_LABEL',
            DIALOG_TITLE:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.FOOTER.FOOTER_FORM.DIALOG_TITLE'
          },
          GENERATE_INVOICE_FORM:{
            DIALOG_TITLE_FINISH_PROFORMA_INVOICE:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.FOOTER.GENERATE_INVOICE_FORM.DIALOG_TITLE',
            DIALOG_FINISH_INVOICE_MESSAGE:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.FOOTER.GENERATE_INVOICE_FORM.DIALOG_FINISH_INVOICE_MESSAGE',
            DIALOG_TITLE_GENERATE_INVOICE:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.FOOTER.GENERATE_INVOICE_FORM.DIALOG_TITLE_GENERATE_INVOICE',
          },
          INDEX:{
            LABEL_TOTAL_FINANCE:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.FOOTER.INDEX.LABEL_TOTAL_FINANCE',
            LABEL_EXP_FINANCE:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.FOOTER.INDEX.LABEL_EXP_FINANCE',
            LABEL_TAX:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.FOOTER.INDEX.LABEL_TAX',
            LABEL_FINAL_FINANCE:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.FOOTER.INDEX.LABEL_FINAL_FINANCE',

          }
        },
        HEADER:{
          FORM:{
            BUTTON_LABEL:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.HEADER.FORM.BUTTON_LABEL',
            SELECT_LABEL:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.HEADER.FORM.SELECT_LABEL',
            INPUT_LABEL:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.HEADER.FORM.INPUT_LABEL',
            INPUT_MESSAGE:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.HEADER.FORM.INPUT_MESSAGE',
            DIALOG_TITLE:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.HEADER.FORM.DIALOG_TITLE'
          },
          HEADER:{
            INVOICE_LABEL_WHOLESALE:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.HEADER.HEADER.INVOICE_LABEL_WHOLESALE',
            INVOICE_LABEL_RETAIL:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.HEADER.HEADER.INVOICE_LABEL_RETAIL',
            LABEL_SHORT_NAME:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.HEADER.HEADER.LABEL_SHORT_NAME',
            LABEL_FULL_NAME:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.HEADER.HEADER.LABEL_FULL_NAME',
            TITLE_INVOICE:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.HEADER.HEADER.TITLE_INVOICE',
            LABEL_CUSTOMER_NAME:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.HEADER.HEADER.LABEL_CUSTOMER_NAME',
            PLACEHOLDER_CUSTOMER_NAME:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.HEADER.HEADER.PLACEHOLDER_CUSTOMER_NAME',
            LABEL_WAREHOUSE_TYPE:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.HEADER.HEADER.LABEL_WAREHOUSE_TYPE',
            LABEL_INVOICE_NUMBER:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.HEADER.HEADER.LABEL_INVOICE_NUMBER',
            PLACEHOLDER_INVOICE_NUMBER:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.HEADER.HEADER.PLACEHOLDER_INVOICE_NUMBER',
            LABEL_INVOICE_DATE:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.HEADER.HEADER.LABEL_INVOICE_DATE',
            TEXT_INVOICE_DATE:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.HEADER.HEADER.TEXT_INVOICE_DATE',
            LABEL_INVOICE_DISCOUNT:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.HEADER.HEADER.LABEL_INVOICE_DISCOUNT'

          },
          NUMBER_DATE:{
            LABEL_INVOICE_NUMBER:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.HEADER.NUMBER_DATE.LABEL_INVOICE_NUMBER',
            LABEL_INVOICE_DISCOUNT:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.HEADER.NUMBER_DATE.LABEL_INVOICE_DISCOUNT',
            LABEL_DATE_OF_INVOICE:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.HEADER.NUMBER_DATE.LABEL_DATE_OF_INVOICE'

          }
        },
        ITEMS:{
          INSERT_FORM:{
            BUTTON_LABEL_ITEM:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.ITEMS.INSERT_FORM.BUTTON_LABEL_ITEM',
            CHECKBOX_LABEL: 'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.ITEMS.INSERT_FORM.CHECKBOX_LABEL',
            BUTTON_LABEL_EDIT:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.ITEMS.INSERT_FORM.BUTTON_LABEL_EDIT',
            INPUT_LABEL_QTY:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.ITEMS.INSERT_FORM.INPUT_LABEL_QTY',
            INPUT_MESSAGE_ENTER_VALID_QTY:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.ITEMS.INSERT_FORM.INPUT_MESSAGE_ENTER_VALID_QTY',
            INPUT_LABEL_SELLING_PRICE:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.ITEMS.INSERT_FORM.INPUT_LABEL_SELLING_PRICE',
            INPUT_MESSAGE_ENTER_VALID_PRICE:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.ITEMS.INSERT_FORM.INPUT_MESSAGE_ENTER_VALID_PRICE',
            INPUT_LABEL_DISCOUNT:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.ITEMS.INSERT_FORM.INPUT_LABEL_DISCOUNT',
            INPUT_MESSAGE_ENTER_VALID_DISCOUNT:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.ITEMS.INSERT_FORM.INPUT_MESSAGE_ENTER_VALID_DISCOUNT',
            LABEL_WAREHOUSE:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.ITEMS.INSERT_FORM.LABEL_WAREHOUSE',
            TITLE_WAREHOUSE:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.ITEMS.INSERT_FORM.TITLE_WAREHOUSE',
            TEXT_QUANTITY:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.ITEMS.INSERT_FORM.TEXT_QUANTITY',
            SELECT_LABEL:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.ITEMS.INSERT_FORM.SELECT_LABEL',
            BUTTON_LABEL_ADD:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.ITEMS.INSERT_FORM.BUTTON_LABEL_ADD'

          },
          TABLE:{
            LABEL_NAME:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.ITEMS.TABLE.LABEL_NAME',
            LABEL_WAREHOUSE:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.ITEMS.TABLE.LABEL_WAREHOUSE',
            LABEL_QTY:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.ITEMS.TABLE.LABEL_QTY',
            LABEL_PRICE:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.ITEMS.TABLE.LABEL_PRICE',
            LABEL_DISCOUNT:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.ITEMS.TABLE.LABEL_DISCOUNT',
            LABEL_BASE_FINANCE:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.ITEMS.TABLE.LABEL_BASE_FINANCE',
            LABEL_TAX:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.ITEMS.TABLE.LABEL_TAX',
            LABEL_TOTAL_FINANCE:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.ITEMS.TABLE.LABEL_TOTAL_FINANCE',

          }
        },
        INDEX:{
          DIALOG_ERROR_MESSAGE:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.INDEX.DIALOG_ERROR_MESSAGE',
          LABEL_SAVE:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.INDEX.LABEL_SAVE',
          LABEL_EDIT:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.INDEX.LABEL_EDIT',
          LABEL_HEADER:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.INDEX.LABEL_HEADER',
          LABEL_FOOTER:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.INDEX.LABEL_FOOTER',
          LABEL_PREVIEW:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.INDEX.LABEL_PREVIEW',
          LABEL_PRINT:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.INDEX.LABEL_PRINT',
          LABEL_FINISH:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.INDEX.LABEL_FINISH',
          DIALOG_SAVE_PROFORMA_INVOICE_MESSAGE:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.INDEX.DIALOG_SAVE_PROFORMA_INVOICE_MESSAGE',
          DIALOG_TITLE:'PROFORMA_INVOICE.VIEW.INSTANCE_VIEW.INDEX.DIALOG_TITLE'
        }
      },
      MAIN_VIEW:{
        FILTER:{
          BUTTON_SHORTCUT_LABEL_CLEAR:'PROFORMA_INVOICE.VIEW.MAIN_VIEW.FILTER.BUTTON_SHORTCUT_LABEL_CLEAR',
          BUTTON_SHORTCUT_LABEL_CUSTOMER: 'PROFORMA_INVOICE.VIEW.MAIN_VIEW.FILTER.BUTTON_SHORTCUT_LABEL_CUSTOMER',

        },
        MAIN_VIEW:{
          LABEL_NEW_INVOICE:'PROFORMA_INVOICE.VIEW.MAIN_VIEW.MAIN_VIEW.LABEL_NEW_INVOICE',
          LABEL_DATE:'PROFORMA_INVOICE.VIEW.MAIN_VIEW.MAIN_VIEW.LABEL_DATE',
          LABEL_INVOICE_NUMBER:'PROFORMA_INVOICE.VIEW.MAIN_VIEW.MAIN_VIEW.LABEL_INVOICE_NUMBER',
          LABEL_CUSTOMER:'PROFORMA_INVOICE.VIEW.MAIN_VIEW.MAIN_VIEW.LABEL_CUSTOMER',
          LABEL_INVOICE:'PROFORMA_INVOICE.VIEW.MAIN_VIEW.MAIN_VIEW.LABEL_INVOICE',
          LABEL_FINANCE_VP:'PROFORMA_INVOICE.VIEW.MAIN_VIEW.MAIN_VIEW.LABEL_FINANCE_VP',
          LABEL_TAX_FINANCE:'PROFORMA_INVOICE.VIEW.MAIN_VIEW.MAIN_VIEW.LABEL_TAX_FINANCE',
          LABEL_FINANCE_MP:'PROFORMA_INVOICE.VIEW.MAIN_VIEW.MAIN_VIEW.LABEL_FINANCE_MP',
          LABEL_STATUS:'PROFORMA_INVOICE.VIEW.MAIN_VIEW.MAIN_VIEW.LABEL_STATUS',
          PROFORMA_INVOICES_INFO_TITLE:'PROFORMA_INVOICE.VIEW.MAIN_VIEW.MAIN_VIEW.PROFORMA_INVOICES_INFO_TITLE',
          DIALOG_CANCEL_PROFORMA_INVOICE_MESSAGE:'PROFORMA_INVOICE.VIEW.MAIN_VIEW.MAIN_VIEW.DIALOG_CANCEL_PROFORMA_INVOICE_MESSAGE',
          DIALOG_CANCEL_PROFORMA_INVOICE_TITLE:'PROFORMA_INVOICE.VIEW.MAIN_VIEW.MAIN_VIEW.DIALOG_CANCEL_PROFORMA_INVOICE_TITLE'

        }
      }
    }

  },

  RETURN_INVOICE: {
    PDF:{
      PDF:{
        PDF_DIALOG_TITLE_RETURN_INVOICE_PDF:'RETURN_INVOICE.PDF.PDF.PDF_DIALOG_TITLE_RETURN_INVOICE_PDF',
        PDF_DIALOG_TITLE:'RETURN_INVOICE.PDF.PDF.PDF_DIALOG_TITLE'
      }
    },
    PREVIEW:{
      PREVIEW:{
        DIALOG_TITLE:'RETURN_INVOICE.PREVIEW.PREVIEW.DIALOG_TITLE'
      }
    },
    VIEW:{
      INSTANCE_VIEW:{
        FOOTER:{
          DUE_DATE_DIALOG:{
            HEADER:'RETURN_INVOICE.VIEW.INSTANCE_VIEW.FOOTER.DUE_DATE_DIALOG.HEADER',
            LABEL:'RETURN_INVOICE.VIEW.INSTANCE_VIEW.FOOTER.DUE_DATE_DIALOG.LABEL'
          },
          FOOTER_FORM:{
            TEXT_AREA_LABEL:'RETURN_INVOICE.VIEW.INSTANCE_VIEW.FOOTER.FOOTER_FORM.TEXT_AREA_LABEL',
            DIALOG_TITLE:'RETURN_INVOICE.VIEW.INSTANCE_VIEW.FOOTER.FOOTER_FORM.DIALOG_TITLE'
          }
        },
        HEADER:{
          FORM:{
            CUSTOMER_VIEW_SHORT_PLACEHOLDER:'RETURN_INVOICE.VIEW.INSTANCE_VIEW.HEADER.FORM.CUSTOMER_VIEW_SHORT_PLACEHOLDER',
            BUTTON_LABEL:'RETURN_INVOICE.VIEW.INSTANCE_VIEW.HEADER.FORM.BUTTON_LABEL',
            SELECT_LABEL:'RETURN_INVOICE.VIEW.INSTANCE_VIEW.HEADER.FORM.SELECT_LABEL',
            SELECT_MESSAGE:'RETURN_INVOICE.VIEW.INSTANCE_VIEW.HEADER.FORM.SELECT_MESSAGE',
            DIALOG_TITLE:'RETURN_INVOICE.VIEW.INSTANCE_VIEW.HEADER.FORM.DIALOG_TITLE'
          },
          HEADER:{
            INVOICE_HEADER_FLAG_WHOLESALE:'RETURN_INVOICE.VIEW.INSTANCE_VIEW.HEADER.HEADER.INVOICE_HEADER_FLAG_WHOLESALE',
            INVOICE_HEADER_FLAG_RETAIL:'RETURN_INVOICE.VIEW.INSTANCE_VIEW.HEADER.HEADER.INVOICE_HEADER_FLAG_RETAIL',
            LABEL_INVOICE:'RETURN_INVOICE.VIEW.INSTANCE_VIEW.HEADER.HEADER.LABEL_INVOICE',
            INVOICE_HEADER_TOOLTIP_CUSTOMER_TITLE:'RETURN_INVOICE.VIEW.INSTANCE_VIEW.HEADER.HEADER.INVOICE_HEADER_TOOLTIP_CUSTOMER_TITLE',
            INVOICE_HEADER_TOOLTIP_WAREHOUSE_TYPE_TITLE:'RETURN_INVOICE.VIEW.INSTANCE_VIEW.HEADER.HEADER.INVOICE_HEADER_TOOLTIP_WAREHOUSE_TYPE_TITLE',
            INVOICE_HEADER_TOOLTIP_DUE_DATES_TITLE:'RETURN_INVOICE.VIEW.INSTANCE_VIEW.HEADER.HEADER.INVOICE_HEADER_TOOLTIP_DUE_DATES_TITLE',
            INVOICE_HEADER_TOOLTIP_ADDITIONAL_EXPENSES_TITLE:'RETURN_INVOICE.VIEW.INSTANCE_VIEW.HEADER.HEADER.INVOICE_HEADER_TOOLTIP_ADDITIONAL_EXPENSES_TITLE',
            LABEL_CUSTOMER_NAME:'RETURN_INVOICE.VIEW.INSTANCE_VIEW.HEADER.HEADER.TITLE_CUSTOMER_NAME',
            PLACEHOLDER_CUSTOMER_NAME:'RETURN_INVOICE.VIEW.INSTANCE_VIEW.HEADER.HEADER.LABEL_CUSTOMER_NAME',
            LABEL_WAREHOUSE_TYPE:'RETURN_INVOICE.VIEW.INSTANCE_VIEW.HEADER.HEADER.LABEL_WAREHOUSE_TYPE',
            LABEL_INVOICE_NUMBER:'RETURN_INVOICE.VIEW.INSTANCE_VIEW.HEADER.HEADER.LABEL_INVOICE_NUMBER',
            PLACEHOLDER_INVOICE_NUMBER:'RETURN_INVOICE.VIEW.INSTANCE_VIEW.HEADER.HEADER.PLACEHOLDER_INVOICE_NUMBER',
            LABEL_INVOICE_DATE:'RETURN_INVOICE.VIEW.INSTANCE_VIEW.HEADER.HEADER.LABEL_INVOICE_DATE',
            PLACEHOLDER_INVOICE_DATE:'RETURN_INVOICE.VIEW.INSTANCE_VIEW.HEADER.HEADER.PLACEHOLDER_INVOICE_DATE'

          },
          NUMBER_DATE:{
            LABEL_INVOICE_NUMBER:'RETURN_INVOICE.VIEWS.INSTANCE_VIEW.HEADER.NUMBER_DATE.LABEL_INVOICE_NUMBER',
            LABEL_DATE_OF_INVOICE:'RETURN_INVOICE.VIEWS.INSTANCE_VIEW.HEADER.NUMBER_DATE.LABEL_DATE_OF_INVOICE',

          }
        },
        ITEMS:{
          INSERT_FORM:{
            BUTTON_LABEL_WAREHOUSES_TAB_ITEM:'RETURN_INVOICE.VIEWS.INSTANCE_VIEW.ITEMS.INSERT_FORM.BUTTON_LABEL_WAREHOUSES_TAB_ITEM',
            BUTTON_LABEL_EDIT:'RETURN_INVOICE.VIEWS.INSTANCE_VIEW.ITEMS.INSERT_FORM.BUTTON_LABEL_EDIT',
            INPUT_MESSAGE_REQUIRED:'RETURN_INVOICE.VIEWS.INSTANCE_VIEW.ITEMS.INSERT_FORM.INPUT_MESSAGE_REQUIRED',
            INPUT_MESSAGE_ENTER_VALID_QTY:'RETURN_INVOICE.VIEWS.INSTANCE_VIEW.ITEMS.INSERT_FORM.INPUT_MESSAGE_ENTER_VALID_QTY',
            INPUT_LABEL_QTY:'RETURN_INVOICE.VIEWS.INSTANCE_VIEW.ITEMS.INSERT_FORM.INPUT_LABEL_QTY',
            INPUT_MESSAGE_REQUIRED_FIELD:'RETURN_INVOICE.VIEWS.INSTANCE_VIEW.ITEMS.INSERT_FORM.INPUT_MESSAGE_REQUIRED_FIELD',
            INPUT_MESSAGE_ENTER_VALID_PRICE:'RETURN_INVOICE.VIEWS.INSTANCE_VIEW.ITEMS.INSERT_FORM.INPUT_MESSAGE_ENTER_VALID_PRICE',
            INPUT_LABEL_SELLING_PRICE:'RETURN_INVOICE.VIEWS.INSTANCE_VIEW.ITEMS.INSERT_FORM.INPUT_LABEL_SELLING_PRICE',
            LABEL_LABEL_WAREHOUSE:'RETURN_INVOICE.VIEWS.INSTANCE_VIEW.ITEMS.INSERT_FORM.LABEL_LABEL_WAREHOUSE',
            LABEL_WAREHOUSE:'RETURN_INVOICE.VIEWS.INSTANCE_VIEW.ITEMS.INSERT_FORM.LABEL_WAREHOUSE',
            LABEL_QUANTITY:'RETURN_INVOICE.VIEWS.INSTANCE_VIEW.ITEMS.INSERT_FORM.LABEL_QUANTITY',
            SELECT_LABEL_WAREHOUSE:'RETURN_INVOICE.VIEWS.INSTANCE_VIEW.ITEMS.INSERT_FORM.SELECT_LABEL_WAREHOUSE',
            SELECT_MESSAGE_REQUIRED_FIELD:'RETURN_INVOICE.VIEWS.INSTANCE_VIEW.ITEMS.INSERT_FORM.SELECT_MESSAGE_REQUIRED_FIELD',
            BUTTON_LABEL_ADD: 'RETURN_INVOICE.VIEWS.INSTANCE_VIEW.ITEMS.INSERT_FORM.BUTTON_LABEL_ADD'

          }
        },
        INDEX:{
          LABEL_HEADER:'RETURN_INVOICE.VIEWS.INSTANCE_VIEW.INDEX.LABEL_HEADER',
          LABEL_FOOTER:'RETURN_INVOICE.VIEWS.INSTANCE_VIEW.INDEX.LABEL_FOOTER',
          LABEL_DUE_DATE:'RETURN_INVOICE.VIEWS.INSTANCE_VIEW.INDEX.LABEL_DUE_DATE',
          LABEL_PREVIEW:'RETURN_INVOICE.VIEWS.INSTANCE_VIEW.INDEX.LABEL_PREVIEW',
          LABEL_PRINT:'RETURN_INVOICE.VIEWS.INSTANCE_VIEW.INDEX.LABEL_PRINT',
          LABEL_FINISH:'RETURN_INVOICE.VIEWS.INSTANCE_VIEW.INDEX.LABEL_FINISH',
          DIALOG_SAVE_RETURN_INVOICE_MESSAGE:'RETURN_INVOICE.VIEWS.INSTANCE_VIEW.INDEX.DIALOG_SAVE_RETURN_INVOICE_MESSAGE',
          DIALOG_ERROR_MESSAGE:'RETURN_INVOICE.VIEWS.INSTANCE_VIEW.INDEX.DIALOG_ERROR_MESSAGE',
          DIALOG_TITLE:'RETURN_INVOICE.VIEWS.INSTANCE_VIEW.INDEX.DIALOG_TITLE',

        }
      },
      MAIN_VIEW:{
        FILTER:{
          BUTTON_LABEL_CLEAR:'RETURN_INVOICE.VIEWS.MAIN_VIEW.FILTER.BUTTON_LABEL_CLEAR',
          BUTTON_LABEL_OPTIONS_CUSTOMER:'RETURN_INVOICE.VIEWS.MAIN_VIEW.FILTER.BUTTON_LABEL_OPTIONS_CUSTOMER',
          INPUT_HELPER_TEXT_DATE_FROM:'RETURN_INVOICE.VIEWS.MAIN_VIEW.FILTER.INPUT_HELPER_TEXT_DATE_FROM',
          INPUT_HELPER_TEXT_DATE_TO:'RETURN_INVOICE.VIEWS.MAIN_VIEW.FILTER.INPUT_HELPER_TEXT_DATE_TO',
          SELECT_LABEL:'RETURN_INVOICE.VIEWS.MAIN_VIEW.FILTER.SELECT_LABEL',

        },
        MAIN_VIEW:{
          LABEL_DATE:'RETURN_INVOICE.VIEWS.MAIN_VIEW.MAIN_VIEW.LABEL_DATE',
          LABEL_INVOICE_NUMBER:'RETURN_INVOICE.VIEWS.MAIN_VIEW.MAIN_VIEW.LABEL_INVOICE_NUMBER',
          LABEL_CUSTOMER:'RETURN_INVOICE.VIEWS.MAIN_VIEW.MAIN_VIEW.LABEL_CUSTOMER',
          LABEL_FINANCE_VP:'RETURN_INVOICE.VIEWS.MAIN_VIEW.MAIN_VIEW.LABEL_FINANCE_VP',
          LABEL_TAX_FINANCE:'RETURN_INVOICE.VIEWS.MAIN_VIEW.MAIN_VIEW.LABEL_TAX_FINANCE',
          LABEL_FINANCE_MP:'RETURN_INVOICE.VIEWS.MAIN_VIEW.MAIN_VIEW.LABEL_FINANCE_MP',
          LABEL_STATUS:'RETURN_INVOICE.VIEWS.MAIN_VIEW.MAIN_VIEW.LABEL_STATUS',
          LABEL_NEW_RETURN_INVOICE:'RETURN_INVOICE.VIEWS.MAIN_VIEW.MAIN_VIEW.LABEL_NEW_RETURN_INVOICE',
          TEXT_RETURN_INVOICE:'RETURN_INVOICE.VIEWS.MAIN_VIEW.MAIN_VIEW.TEXT_RETURN_INVOICE',
          DIALOG_CANCEL_RETURN_INVOICE_MESSAGE:'RETURN_INVOICE.VIEWS.MAIN_VIEW.MAIN_VIEW.DIALOG_CANCEL_RETURN_INVOICE_MESSAGE',
          DIALOG_TITLE:'RETURN_INVOICE.VIEWS.MAIN_VIEW.MAIN_VIEW.DIALOG_TITLE'
        }
      }
    }
  },

  WAREHOUSE: {
    FORM: {
      WAREHOUSE: {
        NAME_LABEL: 'WAREHOUSE.FORM.WAREHOUSE.NAME_LABEL',
        HELPER_TEXT_NAME: 'WAREHOUSE.FORM.WAREHOUSE.HELPER_TEXT_LABEL',
        TYPE_LABEL: 'WAREHOUSE.FORM.WAREHOUSE.TYPE_LABEL',
        HELPER_TEXT_TYPE: 'WAREHOUSE.FORM.WAREHOUSE.HELPER_TEXT_TYPE',
        DESCRIPTION_LABEL: 'WAREHOUSE.FORM.WAREHOUSE.DESCRIPTION_LABEL',
        HELPER_TEXT_DESCRIPTION: 'WAREHOUSE.FORM.WAREHOUSE.HELPER_TEXT_DESCRIPTION',
        DIALOG_TITLE_INSERT: 'WAREHOUSE.FORM.WAREHOUSE.DIALOG_TITLE_INSERT',
        DIALOG_TITLE_EDIT: 'WAREHOUSE.FORM.WAREHOUSE.DIALOG_TITLE_EDIT'
      }
    },
    MODAL: {
      WAREHOUSE_SEARCH: {
        TITLE: 'WAREHOUSE.MODAL.WAREHOUSE_SEARCH.TITLE',
        BUTTON_CANCEL_LABEL: 'WAREHOUSE.MODAL.WAREHOUSE_SEARCH.BUTTON_CANCEL_LABEL',
        BUTTON_OK_LABEL: 'WAREHOUSE.MODAL.WAREHOUSE_SEARCH.BUTTON_OK_LABEL'
      }
    },
    PDF: {
      ITEM: {
        TITLE: 'WAREHOUSE.PDF.ITEM.TITLE'
      },
      ITEMS: {
        TITLE: 'WAREHOUSE.PDF.ITEMS.TITLE'
      },
      SUMMARY: {
        TITLE: 'WAREHOUSE.PDF.SUMMARY.TITLE',
        SUMMARY_TABLE: {
          TOTAL_LABEL: 'WAREHOUSE.PDF.SUMMARY.SUMMARY_TABLE.TOTAL_LABEL',
          OWES_LABEL: 'WAREHOUSE.PDF.SUMMARY.SUMMARY_TABLE.OWES_LABEL',
          CLAIMS_LABEL: 'WAREHOUSE.PDF.SUMMARY.SUMMARY_TABLE.CLAIMS_LABEL',
          BALANCE_LABEL: 'WAREHOUSE.PDF.SUMMARY.SUMMARY_TABLE.BALANCE_LABEL'
        }
      }
    },
    TABS: {
      ARTICLES: {
        ITEMS_TABLE: {
          TH_NAME_LABEL: 'WAREHOUSE.TABS.ARTICLES.ITEMS_TABLE.TH_NAME_LABEL',
          TH_VAT_LABEL: 'WAREHOUSE.TABS.ARTICLES.ITEMS_TABLE.TH_VAT_LABEL',
          TH_SELLING_PRICE_LABEL: 'WAREHOUSE.TABS.ARTICLES.ITEMS_TABLE.TH_SELLING_PRICE_LABEL',
          TH_STACK_PRICE_LABEL: 'WAREHOUSE.TABS.ARTICLES.ITEMS_TABLE.TH_STACK_PRICE_LABEL',
          TH_FINANCE_LABEL: 'WAREHOUSE.TABS.ARTICLES.ITEMS_TABLE.TH_FINANCE_LABEL',
          TH_STACK_LABEL: 'WAREHOUSE.TABS.ARTICLES.ITEMS_TABLE.TH_STACK_LABEL',
          TH_OWES_FINANCE_LABEL: 'WAREHOUSE.TABS.ARTICLES.ITEMS_TABLE.TH_OWES_FINANCE_LABEL',
          TH_CLAIMS_FINANCE_LABEL: 'WAREHOUSE.TABS.ARTICLES.ITEMS_TABLE.TH_CLAIMS_FINANCE_LABEL',
          TH_TRANSACTION_DATE_LABEL: 'WAREHOUSE.TABS.ARTICLES.ITEMS_TABLE.TH_TRANSACTION_DATE_LABEL',
          TABLE_SEARCH_LABEL: 'WAREHOUSE.TABS.ARTICLES.ITEMS_TABLE.TABLE_SEARCH_LABEL',
          BUTTON_PRINT_LABEL : 'WAREHOUSE.TABS.ARTICLES.ITEMS_TABLE.BUTTON_PRINT_LABEL',
          PDF_TITLE_LABEL: 'WAREHOUSE.TABS.ARTICLES.ITEMS_TABLE.PDF_TITLE_LABEL'
        }
      },
      ONE_ARTICLE: {
        FINANCE_PART: {
          TITLE: 'WAREHOUSE.TABS.ONE_ARTICLE.FINANCE_PART.TITLE',
          OWES_LABEL: 'WAREHOUSE.TABS.ONE_ARTICLE.FINANCE_PART.OWES_LABEL',
          CLAIMS_LABEL: 'WAREHOUSE.TABS.ONE_ARTICLE.FINANCE_PART.CLAIMS_LABEL',
          BALANCE_LABEL : 'WAREHOUSE.TABS.ONE_ARTICLE.FINANCE_PART.BALANCE_LABEL'
        },
        GENERAL_DETAILS : {
          TITLE: 'WAREHOUSE.TABS.ONE_ARTICLE.GENERAL_DETAILS.TITLE',
          BUTTON_EDIT_LABEL : 'WAREHOUSE.TABS.ONE_ARTICLE.GENERAL_DETAILS.BUTTON_EDIT_LABEL',
          NAME_PLACEHOLDER: 'WAREHOUSE.TABS.ONE_ARTICLE.GENERAL_DETAILS.NAME_PLACEHOLDER',
          DESCRIPTION_PLACEHOLDER: 'WAREHOUSE.TABS.ONE_ARTICLE.GENERAL_DETAILS.DESCRIPTION_PLACEHOLDER'
        },
        ITEM_LAST_RECORD: {
          DATE_LABEL: 'WAREHOUSE.TABS.ONE_ARTICLE.ITEM_LAST_RECORD.DATE_LABEL',
          QUANTITY_STACK_LABEL: 'WAREHOUSE.TABS.ONE_ARTICLE.ITEM_LAST_RECORD.QUANTITY_STACK_LABEL',
          FINANCE_STACK_LABEL :  'WAREHOUSE.TABS.ONE_ARTICLE.ITEM_LAST_RECORD.FINANCE_STACK_LABEL',
          QUANTITY_OWES_LABEL: 'WAREHOUSE.TABS.ONE_ARTICLE.ITEM_LAST_RECORD.QUANTITY_OWES_LABEL',
          QUANTITY_CLAIMS_LABEL: 'WAREHOUSE.TABS.ONE_ARTICLE.ITEM_LAST_RECORD.QUANTITY_CLAIMS_LABEL',
          FINANCE_OWES_LABEL: 'WAREHOUSE.TABS.ONE_ARTICLE.ITEM_LAST_RECORD.FINANCE_OWES_LABEL',
          FINANCE_CLAIMS_LABEL: 'WAREHOUSE.TABS.ONE_ARTICLE.ITEM_LAST_RECORD.FINANCE_CLAIMS_LABEL'
        },
        ITEM_STATE_TABLE: {
          TH_TRANSACTION_DATE_LABEL : 'WAREHOUSE.TABS.ONE_ARTICLE.ITEM_STATE_TABLE.TH_TRANSACTION_DATE_LABEL',
          TH_DOCUMENT_LABEL: 'WAREHOUSE.TABS.ONE_ARTICLE.ITEM_STATE_TABLE.TH_DOCUMENT_LABEL',
          TH_QUANTITY_OWES_LABEL: 'WAREHOUSE.TABS.ONE_ARTICLE.ITEM_STATE_TABLE.TH_QUANTITY_OWES_LABEL',
          TH_QUANTITY_CLAIMS_LABEL: 'WAREHOUSE.TABS.ONE_ARTICLE.ITEM_STATE_TABLE.TH_QUANTITY_CLAIMS_LABEL',
          TH_QUANTITY_STACK_LABEL: 'WAREHOUSE.TABS.ONE_ARTICLE.ITEM_STATE_TABLE.TH_QUANTITY_STACK_LABEL',
          TH_PRICE_STACK_LABEL: 'WAREHOUSE.TABS.ONE_ARTICLE.ITEM_STATE_TABLE.TH_PRICE_STACK_LABEL',
          TH_FINANCE_STACK_LABEL : 'WAREHOUSE.TABS.ONE_ARTICLE.ITEM_STATE_TABLE.TH_FINANCE_STACK_LABEL',
          BUTTON_EDIT_LABEL: 'WAREHOUSE.TABS.ONE_ARTICLE.ITEM_STATE_TABLE.BUTTON_EDIT_LABEL',
          BUTTON_PRINT_LABEL: 'WAREHOUSE.TABS.ONE_ARTICLE.ITEM_STATE_TABLE.BUTTON_PRINT_LABEL',
          PDF_DIALOG_TITLE: 'WAREHOUSE.TABS.ONE_ARTICLE.ITEM_STATE_TABLE.PDF_DIALOG_TITLE'
        },
        TABLE_SEARCH: {
          ITEM_NAME_LABEL: 'WAREHOUSE.TABS.ONE_ARTICLE.TABLE_SEARCH.ITEM_NAME_LABEL',
          ITEM_CODE_LABEL: 'WAREHOUSE.TABS.ONE_ARTICLE.TABLE_SEARCH.ITEM_CODE_LABEL',
          DATE_FROM_HELPER_TEXT : 'WAREHOUSE.TABS.ONE_ARTICLE.TABLE_SEARCH.DATE_FROM_HELPER_TEXT',
          DATE_TO_HELPER_TEXT : 'WAREHOUSE.TABS.ONE_ARTICLE.TABLE_SEARCH.DATE_TO_HELPER_TEXT',
          BUTTON_CLEAR_LABEL: 'WAREHOUSE.TABS.ONE_ARTICLE.TABLE_SEARCH.BUTTON_CLEAR_LABEL',
          BUTTON_CUSTOMER_LABEL: 'WAREHOUSE.TABS.ONE_ARTICLE.TABLE_SEARCH.BUTTON_CUSTOMER_LABEL'
        }
      },
      TRANSFER: {
        FORM: {
          TRANSFER : {
            TITLE: 'WAREHOUSE.TABS.TRANSFER.FORM.TRANSFER.TITLE',
            FROM_WAREHOUSE_LABEL: 'WAREHOUSE.TABS.TRANSFER.FORM.TRANSFER.FROM_WAREHOUSE_LABEL',
            TO_WAREHOUSE_LABEL: 'WAREHOUSE.TABS.TRANSFER.FORM.TRANSFER.TO_WAREHOUSE_LABEL',
            TRANSFER_DATE_LABEL: 'WAREHOUSE.TABS.TRANSFER.FORM.TRANSFER.TRANSFER_DATE_LABEL',
            DIALOG_FINISH_TITLE: 'WAREHOUSE.TABS.TRANSFER.FORM.TRANSFER.DIALOG_FINISH_TITLE',
            DIALOG_FINISH_MESSAGE: 'WAREHOUSE.TABS.TRANSFER.FORM.TRANSFER.DIALOG_FINISH_MESSAGE'
          },
          TRANSFER_ITEM: {
            AUTOCOMPLETE_LABEL: 'WAREHOUSE.TABS.TRANSFER.FORM.TRANSFER_ITEM.AUTOCOMPLETE_LABEL',
            AUTOCOMPLETE_HELPER_TEXT : 'WAREHOUSE.TABS.TRANSFER.FORM.TRANSFER_ITEM.AUTOCOMPLETE_HELPER_TEXT',
            BUTTON_ITEM_LABEL: 'WAREHOUSE.TABS.TRANSFER.FORM.TRANSFER_ITEM.BUTTON_ITEM_LABEL',
            QTY_ON_STACK_LABEL: 'WAREHOUSE.TABS.TRANSFER.FORM.TRANSFER_ITEM.QTY_ON_STACK_LABEL',
            BUTTON_ADD_LABEL: 'WAREHOUSE.TABS.TRANSFER.FORM.TRANSFER_ITEM.BUTTON_ADD_LABEL'
          },
          TRANSFER_ITEMS_TABLE: {
            TH_ITEM_LABEL: 'WAREHOUSE.TABS.TRANSFER.FORM.TRANSFER_ITEMS_TABLE.TH_ITEM_LABEL',
            TH_QTY_LABEL : 'WAREHOUSE.TABS.TRANSFER.FORM.TRANSFER_ITEMS_TABLE.TH_QTY_LABEL',
          }
        },
        PDF: {
          HEADER: {
            HEADER: {
              TRANSFER_DATE_LABEL: 'WAREHOUSE.TABS.TRANSFER.PDF.HEADER.TRANSFER_DATE_LABEL'
            }
          },
          PDF: {
            TITLE: 'WAREHOUSE.TABS.TRANSFER.PDF.PDF.TITLE',
            TH_NAME_LABEL : 'WAREHOUSE.TABS.TRANSFER.PDF.PDF.TH_NAME_LABEL',
            TH_QTY_LABEL: 'WAREHOUSE.TABS.TRANSFER.PDF.PDF.TH_QTY_LABEL',
            DIALOG_TITLE: 'WAREHOUSE.TABS.TRANSFER.PDF.PDF.DIALOG_TITLE'
          }
        },
        PREVIEW: {
          PREVIEW: {
            NO_TABLE_DATA_MESSAGE : 'WAREHOUSE.TABS.TRANSFER.PREVIEW.PREVIEW.NO_TABLE_DATA_MESSAGE',
            DIALOG_TITLE: 'WAREHOUSE.TABS.TRANSFER.PREVIEW.PREVIEW.DIALOG_TITLE'
          }
        },
        DASHBOARD: {
          TH_DATE_LABEL: 'WAREHOUSE.TABS.TRANSFER.DASHBOARD.TH_DATE_LABEL',
          TH_FROM_WAREHOUSE_LABEL: 'WAREHOUSE.TABS.TRANSFER.DASHBOARD.TH_FROM_WAREHOUSE_LABEL',
          TH_TO_WAREHOUSE_LABEL: 'WAREHOUSE.TABS.TRANSFER.DASHBOARD.TH_TO_WAREHOUSE_LABEL',
          TH_STATUS_LABEL: 'WAREHOUSE.TABS.TRANSFER.DASHBOARD.TH_STATUS_LABEL',
          BUTTON_ADD_LABEL: 'WAREHOUSE.TABS.TRANSFER.DASHBOARD.BUTTON_ADD_LABEL',
          DIALOG_TITLE_SAVE: 'WAREHOUSE.TABS.TRANSFER.DASHBOARD.DIALOG_TITLE_SAVE',
          DIALOG_TITLE_CANCEL: 'WAREHOUSE.TABS.TRANSFER.DASHBOARD.DIALOG_TITLE_CANCEL',
          DIALOG_SAVE_MESSAGE: 'WAREHOUSE.TABS.TRANSFER.DASHBOARD.DIALOG_SAVE_MESSAGE',
          DIALOG_CANCEL_MESSAGE: 'WAREHOUSE.TABS.TRANSFER.DASHBOARD.DIALOG_CANCEL_MESSAGE'
        },
        FILTER: {
          BUTTON_CLEAR_LABEL : 'WAREHOUSE.TABS.TRANSFER.FILTER.BUTTON_CLEAR_LABEL',
          BUTTON_TO_WAREHOUSE_LABEL: 'WAREHOUSE.TABS.TRANSFER.FILTER.BUTTON_TO_WAREHOUSE_LABEL',
          DATE_TO_HELPER_TEXT: 'WAREHOUSE.TABS.TRANSFER.FILTER.DATE_TO_HELPER_TEXT',
          DATE_FROM_HELPER_TEXT: 'WAREHOUSE.TABS.TRANSFER.FILTER.DATE_FROM_HELPER_TEXT',
          STATUS_LABEL: 'WAREHOUSE.TABS.TRANSFER.FILTER.STATUS_LABEL'
        }
      },
      WAREHOUSE: {
        TABLE: {
          BUTTON_PRINT_LABEL: 'WAREHOUSE.TABS.WAREHOUSE.TABLE.BUTTON_PRINT_LABEL',
          TH_WAREHOUSE_NUMBER_LABEL: 'WAREHOUSE.TABS.WAREHOUSE.TABLE.TH_WAREHOUSE_NUMBER_LABEL',
          TH_DATE_LABEL: 'WAREHOUSE.TABS.WAREHOUSE.TABLE.TH_DATE_LABEL',
          TH_DESCRIPTION_LABEL: 'WAREHOUSE.TABS.WAREHOUSE.TABLE.TH_DESCRIPTION_LABEL',
          TH_DATE_DOCUMENT_LABEL: 'WAREHOUSE.TABS.WAREHOUSE.TABLE.TH_DATE_DOCUMENT_LABEL',
          TH_OWES_LABEL: 'WAREHOUSE.TABS.WAREHOUSE.TABLE.TH_OWES_LABEL',
          TH_CLAIMS_LABEL : 'WAREHOUSE.TABS.WAREHOUSE.TABLE.TH_CLAIMS_LABEL',
          TH_BALANCE_LABEL: 'WAREHOUSE.TABS.WAREHOUSE.TABLE.TH_BALANCE_LABEL',
          SUMMARY_CUMULATIVE_LABEL: 'WAREHOUSE.TABS.WAREHOUSE.TABLE.SUMMARY_CUMULATIVE_LABEL',
          SUMMARY_OWES_LABEL: 'WAREHOUSE.TABS.WAREHOUSE.TABLE.SUMMARY_OWES_LABEL',
          SUMMARY_CLAIMS_LABEL: 'WAREHOUSE.TABS.WAREHOUSE.TABLE.SUMMARY_CLAIMS_LABEL',
          SUMMARY_TOTAL_LABEL: 'WAREHOUSE.TABS.WAREHOUSE.TABLE.SUMMARY_TOTAL_LABEL',
          PDF_DIALOG_TITLE : 'WAREHOUSE.TABS.WAREHOUSE.TABLE.PDF_DIALOG_TITLE'
        },
        TABLE_SEARCH : {
          DATE_FROM_HELPER_TEXT: 'WAREHOUSE.TABS.WAREHOUSE.TABLE_SEARCH.DATE_FROM_HELPER_TEXT',
          DATE_TO_HELPER_TEXT: 'WAREHOUSE.TABS.WAREHOUSE.TABLE_SEARCH.DATE_TO_HELPER_TEXT',
        }
      }
    },
    VIEWS: {
      WAREHOUSE_EMPTY_VIEW: {
        MESSAGE: 'WAREHOUSE.VIEWS.WAREHOUSE_EMPTY_VIEW.MESSAGE',
        BUTTON_CREATE_NEW_LABEL: 'WAREHOUSE.VIEWS.WAREHOUSE_EMPTY_VIEW.BUTTON_CREATE_NEW_LABEL'
      },
      WAREHOUSE_VIEW_SHORT: {
        NAME_PLACEHOLDER : 'WAREHOUSE.VIEWS.WAREHOUSE_VIEW_SHORT.NAME_PLACEHOLDER',
        DESCRIPTION_PLACEHOLDER : 'WAREHOUSE.VIEWS.WAREHOUSE_VIEW_SHORT.DESCRIPTION_PLACEHOLDER',
        ERROR_MESSAGE: 'WAREHOUSE.VIEWS.WAREHOUSE_VIEW_SHORT.ERROR_MESSAGE'
      }
    },
    SEARCH_VIEW_WAREHOUSE: {
      SEARCH_VIEW_HELPER_TEXT: 'WAREHOUSE.SEARCH_VIEW_WAREHOUSE.SEARCH_VIEW_HELPER_TEXT',
      BARCODE_LABEL: 'WAREHOUSE.SEARCH_VIEW_WAREHOUSE.BARCODE_LABEL',
      CODE_LABEL: 'WAREHOUSE.SEARCH_VIEW_WAREHOUSE.CODE_LABEL',
    },
    WAREHOUSE_DASHBOARD: {
      TAB_NAME_ITEM: 'WAREHOUSE.WAREHOUSE_DASHBOARD.TAB_NAME_ITEM',
      TAB_NAME_ITEMS: 'WAREHOUSE.WAREHOUSE_DASHBOARD.TAB_NAME_ITEMS',
      TAB_NAME_WAREHOUSE: 'WAREHOUSE.WAREHOUSE_DASHBOARD.TAB_NAME_WAREHOUSE',
      TAB_NAME_TRANSFER: 'WAREHOUSE.WAREHOUSE_DASHBOARD.TAB_NAME_TRANSFER'
    }
  },

}